"use client";
import React,{useCallback,useEffect,useMemo,useRef,useState}from"react";
import{createPortal}from"react-dom";
import styles from "./DrawingIconPicker.module.css";
import{EMOJI_CATEGORIES,ICON_FAMILY_LABELS,ICON_SYMBOLS,STICKER_SYMBOLS,type DrawingIconFamily}from"./drawingIconPickerData";
interface Props{anchorRef:React.RefObject<HTMLButtonElement|null>;open:boolean;onClose:()=>void;onSelect:(symbol:string)=>void}
const W=354,MAX_H=679,GAP=8;
const symbolStyle:React.CSSProperties={width:"100%",minWidth:0,height:38,display:"grid",placeItems:"center",padding:0,border:0,borderRadius:4,background:"transparent",color:"inherit",fontSize:24,lineHeight:1,cursor:"pointer",fontFamily:"'Noto Color Emoji','Apple Color Emoji','Segoe UI Emoji',sans-serif"};
const Grid=({symbols,onSelect}:{symbols:readonly string[];onSelect:(s:string)=>void})=><div style={{display:"grid",gridTemplateColumns:"repeat(9,minmax(0,1fr))",padding:"8px 10px 16px"}}>{symbols.map((s,i)=><button key={s+"-"+i} type="button" title={s} aria-label={"Icon "+s} onClick={()=>onSelect(s)} style={symbolStyle} onMouseEnter={e=>e.currentTarget.style.background="rgba(148,163,184,.16)"} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>{s}</button>)}</div>;
export const DrawingIconPicker:React.FC<Props>=({anchorRef,open,onClose,onSelect})=>{
 const[family,setFamily]=useState<DrawingIconFamily>("emojis");
 const[activeCategory,setActiveCategory]=useState(EMOJI_CATEGORIES[0].id);
 const[position,setPosition]=useState({top:GAP,left:GAP,height:MAX_H});
 const scrollRef=useRef<HTMLDivElement>(null);
 const sectionRefs=useRef<Record<string,HTMLDivElement|null>>({});
 const updatePosition=useCallback(()=>{const r=anchorRef.current?.getBoundingClientRect();if(!r||typeof window==="undefined")return;const height=Math.min(MAX_H,Math.max(320,window.innerHeight-GAP*2));setPosition({height,top:Math.max(GAP,Math.min(r.top-34,window.innerHeight-height-GAP)),left:Math.max(GAP,Math.min(r.right+8,window.innerWidth-W-GAP))});},[anchorRef]);
 useEffect(()=>{if(!open||typeof window==="undefined")return;updatePosition();const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()};window.addEventListener("resize",updatePosition);window.addEventListener("scroll",updatePosition,true);window.addEventListener("keydown",key);return()=>{window.removeEventListener("resize",updatePosition);window.removeEventListener("scroll",updatePosition,true);window.removeEventListener("keydown",key)}},[onClose,open,updatePosition]);
 useEffect(()=>{if(!open||family!=="emojis")return;const root=scrollRef.current;if(!root||typeof IntersectionObserver==="undefined")return;const observer=new IntersectionObserver(entries=>{const visible=entries.filter(e=>e.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];const id=visible?.target.getAttribute("data-icon-category");if(id)setActiveCategory(id)},{root,threshold:[.15,.45,.75]});Object.values(sectionRefs.current).forEach(el=>el&&observer.observe(el));return()=>observer.disconnect()},[family,open]);
 const flat=useMemo(()=>family==="stickers"?STICKER_SYMBOLS:ICON_SYMBOLS,[family]);
 const select=useCallback((s:string)=>{onSelect(s);onClose()},[onClose,onSelect]);
 const jump=useCallback((id:string)=>{setActiveCategory(id);sectionRefs.current[id]?.scrollIntoView({block:"start",behavior:"smooth"})},[]);
 if(!open||typeof document==="undefined")return null;
 return createPortal(<div className="gp-cursor-dropdown-portal gp-icon-picker" role="menu" aria-label="Icons" data-icon-family={family} onMouseDown={e=>e.stopPropagation()} style={{position:"fixed",zIndex:100000,width:W,height:position.height,top:position.top,left:position.left,display:"flex",flexDirection:"column",overflow:"hidden",border:"1px solid rgba(148,163,184,.24)",borderRadius:6,background:"var(--gp-bg-panel,#0d2136)",color:"var(--gp-text-primary,#e2e8f0)",boxShadow:"0 10px 28px rgba(0,0,0,.46)",fontFamily:"-apple-system,BlinkMacSystemFont,'Trebuchet MS',Roboto,Ubuntu,sans-serif"}}>
  <div aria-label="Emoji categories" style={{height:48,minHeight:48,display:"grid",gridTemplateColumns:"repeat(8,38px)",justifyContent:"center",alignItems:"center",borderBottom:"1px solid rgba(148,163,184,.2)"}}>{EMOJI_CATEGORIES.map(c=><button key={c.id} type="button" aria-label={c.label} aria-pressed={family==="emojis"&&activeCategory===c.id} title={c.label} onClick={()=>{if(family!=="emojis")setFamily("emojis");requestAnimationFrame(()=>jump(c.id))}} style={{width:38,height:38,border:0,borderRadius:4,background:family==="emojis"&&activeCategory===c.id?"rgba(41,98,255,.2)":"transparent",color:family==="emojis"&&activeCategory===c.id?"#7aa2ff":"var(--gp-text-secondary,#aeb4bf)",fontSize:19,cursor:"pointer"}}>{c.navSymbol}</button>)}</div>
  <div ref={scrollRef} className={styles.scrollArea} data-icon-picker-scroll style={{flex:1,minHeight:0,overflowY:"auto",overflowX:"hidden",overscrollBehavior:"contain"}}>{family==="emojis"?EMOJI_CATEGORIES.map(c=><div key={c.id} ref={el=>{sectionRefs.current[c.id]=el}} data-icon-category={c.id} style={{scrollMarginTop:4}}><div style={{padding:"12px 12px 5px",color:"var(--gp-text-muted,#8f9aaa)",fontSize:10,fontWeight:600,letterSpacing:".06em",textTransform:"uppercase"}}>{c.label}</div><Grid symbols={c.symbols} onSelect={select}/></div>):<Grid symbols={flat} onSelect={select}/>}</div>
  <div role="tablist" aria-label="Icon families" style={{height:48,minHeight:48,display:"flex",justifyContent:"center",alignItems:"stretch",borderTop:"1px solid rgba(148,163,184,.2)"}}>{(["emojis","stickers","icons"]as const).map(tab=><button key={tab} type="button" role="tab" aria-selected={family===tab} onClick={()=>{setFamily(tab);scrollRef.current?.scrollTo({top:0})}} style={{minWidth:tab==="stickers"?82:72,padding:"0 12px",border:0,borderBottom:family===tab?"2px solid #2962ff":"2px solid transparent",background:"transparent",color:family===tab?"#7aa2ff":"var(--gp-text-primary,#e2e8f0)",fontSize:14,cursor:"pointer"}}>{ICON_FAMILY_LABELS[tab]}</button>)}</div>
 </div>,document.body)
};
