import type { CSSProperties } from "react";

export const TV = {
  bg: "var(--gp-bg-toolbar)",
  border: "1px solid var(--gp-border-color-light)",
  shadow: "var(--shadow-elevated)",
  radius: "var(--gp-radius-md)",
  tabActiveBg: "var(--gp-bg-active)",
  tabText: "var(--gp-text-primary)",
  tabMuted: "var(--gp-text-muted)",
  tabActiveColor: "var(--gp-text-primary)",
  labelColor: "var(--gp-text-secondary)",
  valueColor: "var(--gp-text-primary)",
  bullColor: "#26a69a",
  bearColor: "#ef5350",
  rowHoverBg: "var(--gp-bg-hover)",
  divider: "1px solid var(--gp-border-color-light)",
  iconBtn: "var(--gp-text-muted)",
  iconBtnHover: "var(--gp-text-primary)",
  trashHover: "#f23645",
} as const;

export const iconBtnStyle: CSSProperties = {
  width: "24px",
  height: "24px",
  minWidth: "24px",
  padding: 0,
  border: "none",
  borderRadius: "var(--gp-radius-xs)",
  background: "transparent",
  cursor: "pointer",
  color: TV.iconBtn,
  fontSize: 12,
  lineHeight: 1,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  flexShrink: 0,
  boxSizing: "border-box",
  transition: "color var(--gp-transition-fast), background var(--gp-transition-fast)",
};

export const toolbarIconBtnStyle: CSSProperties = {
  width: "28px",
  height: "28px",
  minWidth: "28px",
  padding: 0,
  border: "none",
  background: "transparent",
  cursor: "pointer",
  color: TV.iconBtn,
  fontSize: 15,
  lineHeight: 1,
  display: "inline-flex",
  alignItems: "center",
  justifyContent: "center",
  boxSizing: "border-box",
  transition: "color var(--gp-transition-fast), background var(--gp-transition-fast)",
  borderRadius: "var(--gp-radius-sm)",
};

export const menuItemStyle: CSSProperties = {
  display: "flex",
  alignItems: "center",
  gap: "10px",
  width: "100%",
  padding: "8px 12px",
  background: "transparent",
  border: "none",
  color: "var(--gp-text-primary)",
  fontSize: "12px",
  textAlign: "left",
  cursor: "pointer",
  transition: "background var(--gp-transition-fast)",
  borderRadius: "var(--gp-radius-xs)",
};
