const TOOL_LABELS: Record<string, string> = {
  line: "Trendline",
  horizontal_line: "Horizontal Line",
  vertical_line: "Vertical Line",
  arrow: "Arrow",
  trend_angle: "Trend Angle",
  ray: "Ray",
  x_line: "Extended Line",
  horizontal_ray: "Horizontal Ray",
  polyline: "Polyline",
  path: "Path",
  circle: "Circle",
  ellipse: "Ellipse",
  triangle: "Triangle",
  arc: "Arc",
  double_curve: "Double Curve",
  curve: "Curve",
  crosshair: "Crosshair",
  arrow_marker: "Arrow Marker",
  arrow_mark_up: "Arrow Mark Up",
  arrow_mark_down: "Arrow Mark Down",
  projection: "Projection",
  date_range: "Date Range",
  price_range: "Price Range",
  date_price_range: "Date & Price Range",
  long_position: "Long Position",
  short_position: "Short Position",
  parallel_channel: "Parallel Channel",
  regression_trend: "Regression Trend",
  flat_top_bottom: "Flat Top & Bottom",
  disjoint_channel: "Disjoint Channel",
  pitchfork: "Andrews' Pitchfork",
  schiff_pitchfork: "Schiff Pitchfork",
  modified_schiff_pitchfork: "Modified Schiff Pitchfork",
  inside_pitchfork: "Inside Pitchfork",
  fib_retracement: "Fib Retracement",
  trend_based_fib_extension: "Trend-Based Fib Extension",
  fib_channel: "Fib Channel",
  fib_time_zone: "Fib Time Zone",
  fib_speed_resistance_fan: "Fib Speed/Resistance Fan",
  trend_based_fib_time: "Trend-Based Fib Time",
  fib_circles: "Fib Circles",
  fib_spiral: "Fib Spiral",
  fib_speed_resistance_arcs: "Fib Speed/Resistance Arcs",
  fib_wedge: "Fib Wedge",
  pitchfan: "Pitchfan",
  gann_box: "Gann Box",
  gann_square_fixed: "Gann Square Fixed",
  gann_square: "Gann Square",
  gann_fan: "Gann Fan",
  xabcd_pattern: "XABCD Pattern",
  cypher_pattern: "Cypher Pattern",
  abcd_pattern: "ABCD Pattern",
  triangle_pattern: "Triangle Pattern",
  three_drives_pattern: "Three Drives",
  head_and_shoulders: "Head & Shoulders",
  elliott_impulse_wave: "Elliott Impulse Wave",
  elliott_triangle_wave: "Elliott Triangle Wave",
  elliott_triple_combo_wave: "Elliott Triple Combo Wave",
  elliott_correction_wave: "Elliott Correction Wave",
  elliott_double_combo_wave: "Elliott Double Combo Wave",
  cyclic_lines: "Cyclic Lines",
  time_cycles: "Time Cycles",
  sine_line: "Sine Line",
  position_forecast: "Position Forecast",
  bar_pattern: "Bar Pattern",
  ghost_feed: "Ghost Feed",
  anchored_vwap: "Anchored VWAP",
  sector: "Sector",
  anchored_volume_profile: "Anchored Volume Profile",
  fixed_range_volume_profile: "Fixed Range Volume Profile",
  signpost: "Signpost",
};

export const getDrawingLabel = (type: string, index: number): string => `${TOOL_LABELS[type] ?? type} ${index + 1}`;

export const getToolLabel = (type: string): string => TOOL_LABELS[type] ?? type;
