import type { AdvancedIndicatorsState } from "../../../config/indicators/advancedIndicatorsTypes";
import type { ObjectTreeItem } from "./objectTreeItemTypes";

export type AdvancedIndicatorLabelMeta = {
  label: string;
  kind: ObjectTreeItem["kind"];
  color: string;
};

export const ADVANCED_INDICATOR_LABELS: Record<keyof AdvancedIndicatorsState, AdvancedIndicatorLabelMeta> = {
  rsi: { label: "RSI", kind: "indicator", color: "#7E57C2" },
  macd: { label: "MACD", kind: "indicator", color: "#FF9F04" },
  bollinger: { label: "Bollinger Bands", kind: "overlay", color: "#2962FF" },
  stochastic: { label: "Stochastic", kind: "indicator", color: "#2962FF" },
  atr: { label: "ATR 14", kind: "indicator", color: "#d50000" },
  atr20: { label: "ATR 20", kind: "indicator", color: "#fb7185" },
  natr14: { label: "NATR 14", kind: "indicator", color: "#22c55e" },
  donchian: { label: "Donchian Channels", kind: "overlay", color: "#06b6d4" },
  keltner: { label: "Keltner Channels", kind: "overlay", color: "#f59e0b" },
  hv10: { label: "HV 10", kind: "indicator", color: "#38bdf8" },
  hv20: { label: "HV 20", kind: "indicator", color: "#22c55e" },
  hv30: { label: "HV 30", kind: "indicator", color: "#f59e0b" },
  hv60: { label: "HV 60", kind: "indicator", color: "#a78bfa" },
  hv90: { label: "HV 90", kind: "indicator", color: "#fb7185" },
  hv252: { label: "HV 252", kind: "indicator", color: "#eab308" },
  stdDev20: { label: "Std Dev 20", kind: "indicator", color: "#14b8a6" },
  chaikinVol: { label: "Chaikin Volatility", kind: "indicator", color: "#f97316" },
  cci: { label: "CCI 20", kind: "indicator", color: "#00E676" },
  cci14: { label: "CCI 14", kind: "indicator", color: "#f59e0b" },
  cci20: { label: "CCI 20", kind: "indicator", color: "#00E676" },
  mfi14: { label: "MFI 14", kind: "indicator", color: "#10b981" },
  williamsR: { label: "Williams %R 14", kind: "indicator", color: "#FFEB3B" },
  williamsR14: { label: "Williams %R 14", kind: "indicator", color: "#FFEB3B" },
  roc: { label: "ROC 10", kind: "indicator", color: "#2196F3" },
  roc10: { label: "ROC 10", kind: "indicator", color: "#2196F3" },
  roc20: { label: "ROC 20", kind: "indicator", color: "#38BDF8" },
  momentum10: { label: "Momentum 10", kind: "indicator", color: "#FF2E93" },
  momentum20: { label: "Momentum 20", kind: "indicator", color: "#F97316" },
  cmo14: { label: "CMO 14", kind: "indicator", color: "#FB7185" },
  dymi: { label: "DYMI", kind: "indicator", color: "#A855F7" },
  ultimateOsc: { label: "Ultimate Osc", kind: "indicator", color: "#F43F5E" },
  dpo20: { label: "DPO 20", kind: "indicator", color: "#06B6D4" },
  tsi: { label: "TSI", kind: "indicator", color: "#8B5CF6" },
  awesomeOsc: { label: "Awesome Osc", kind: "indicator", color: "#26a69a" },
  acOsc: { label: "AC Osc", kind: "indicator", color: "#26a69a" },
  rvi: { label: "RVI", kind: "indicator", color: "#22d3ee" },
  fisherTransform: { label: "Fisher Transform", kind: "indicator", color: "#e879f9" },
  elderBullBear: { label: "Elder Bull/Bear", kind: "indicator", color: "#f97316" },
  coppock: { label: "Coppock", kind: "indicator", color: "#84cc16" },
  ppo: { label: "PPO", kind: "indicator", color: "#38bdf8" },
  apo: { label: "APO", kind: "indicator", color: "#f97316" },
  parabolicSar: { label: "Parabolic SAR", kind: "overlay", color: "#facc15" },
  adx: { label: "ADX", kind: "indicator", color: "#22c55e" },
  aroon: { label: "Aroon", kind: "indicator", color: "#38bdf8" },
  aroonOsc: { label: "Aroon Osc", kind: "indicator", color: "#a78bfa" },
  supertrend: { label: "Supertrend", kind: "overlay", color: "#22c55e" },
  vortex: { label: "Vortex", kind: "indicator", color: "#38bdf8" },
  trix: { label: "TRIX", kind: "indicator", color: "#f97316" },
  stc: { label: "STC", kind: "indicator", color: "#a855f7" },
  massIndex: { label: "Mass Index", kind: "indicator", color: "#f59e0b" },
  kst: { label: "KST", kind: "indicator", color: "#38bdf8" },
  linearRegression: { label: "Linear Regression", kind: "overlay", color: "#818cf8" },
  ulcerIndex: { label: "Ulcer Index", kind: "indicator", color: "#e11d48" },
  obv: { label: "OBV", kind: "indicator", color: "#FF5722" },
  adLine: { label: "A/D Line", kind: "indicator", color: "#10b981" },
  cmf20: { label: "CMF 20", kind: "indicator", color: "#22c55e" },
  nvi: { label: "NVI", kind: "indicator", color: "#38bdf8" },
  pvi: { label: "PVI", kind: "indicator", color: "#f59e0b" },
  chaikinOsc: { label: "Chaikin Oscillator", kind: "indicator", color: "#f97316" },
  volumeOsc: { label: "Volume Oscillator", kind: "indicator", color: "#a855f7" },
  vroc14: { label: "VROC 14", kind: "indicator", color: "#22d3ee" },
  klinger: { label: "Klinger Oscillator", kind: "indicator", color: "#0ea5e9" },
  elderForceIndex: { label: "Elder Force Index", kind: "indicator", color: "#f43f5e" },
  eom14: { label: "EOM 14", kind: "indicator", color: "#8b5cf6" },
  volumeProfile: { label: "Volume Profile", kind: "overlay", color: "#0ea5e9" },
  pivotPointsStandard: { label: "Pivot Points Standard", kind: "overlay", color: "#38bdf8" },
  pivotPointsFibonacci: { label: "Pivot Points Fibonacci", kind: "overlay", color: "#f59e0b" },
  movingAverageCrosses: { label: "Croisements de moyennes", kind: "overlay", color: "#22c55e" },
  vwap: { label: "VWAP", kind: "overlay", color: "#14b8a6" },
  fiftyTwoWeekHigh: { label: "52W High", kind: "overlay", color: "#f97316" },
  fiftyTwoWeekLow: { label: "52W Low", kind: "overlay", color: "#38bdf8" },
  ath: { label: "ATH", kind: "overlay", color: "#facc15" },
  atl: { label: "ATL", kind: "overlay", color: "#a78bfa" },
  breakoutResistance: { label: "Breakout résistance", kind: "overlay", color: "#22c55e" },
  breakdownSupport: { label: "Breakdown support", kind: "overlay", color: "#f43f5e" },
  gapUp: { label: "Gap Up", kind: "overlay", color: "#22d3ee" },
  gapDown: { label: "Gap Down", kind: "overlay", color: "#fb7185" },
  trueGapUp: { label: "True Gap Up", kind: "overlay", color: "#67e8f9" },
  trueGapDown: { label: "True Gap Down", kind: "overlay", color: "#fda4af" },
  gapPct: { label: "Gap %", kind: "overlay", color: "#e0f2fe" },
  consecutiveUpDays: { label: "Jours hausse", kind: "overlay", color: "#16a34a" },
  consecutiveDownDays: { label: "Jours baisse", kind: "overlay", color: "#dc2626" },
  insideBar: { label: "Inside Bar", kind: "overlay", color: "#a78bfa" },
  outsideBar: { label: "Outside Bar", kind: "overlay", color: "#f59e0b" },
  doji: { label: "Doji", kind: "overlay", color: "#94a3b8" },
  longLeggedDoji: { label: "Long-legged Doji", kind: "overlay", color: "#fbbf24" },
  rickshawMan: { label: "Rickshaw Man", kind: "overlay", color: "#c084fc" },
  dragonflyDoji: { label: "Dragonfly Doji", kind: "overlay", color: "#22c55e" },
  gravestoneDoji: { label: "Gravestone Doji", kind: "overlay", color: "#f43f5e" },
  tristar: { label: "Tristar", kind: "overlay", color: "#38bdf8" },
  hammer: { label: "Hammer", kind: "overlay", color: "#22c55e" },
  hangingMan: { label: "Hanging Man", kind: "overlay", color: "#f97316" },
  takuri: { label: "Takuri", kind: "overlay", color: "#14b8a6" },
  invertedHammer: { label: "Inverted Hammer", kind: "overlay", color: "#38bdf8" },
  shootingStar: { label: "Shooting Star", kind: "overlay", color: "#f43f5e" },
  marubozuBull: { label: "Marubozu Bull", kind: "overlay", color: "#16a34a" },
  marubozuBear: { label: "Marubozu Bear", kind: "overlay", color: "#dc2626" },
  spinningTop: { label: "Spinning Top", kind: "overlay", color: "#a3a3a3" },
  ichimoku: { label: "Ichimoku", kind: "overlay", color: "#2962FF" },
  stochRsi: { label: "Stochastic RSI", kind: "indicator", color: "#00BCD4" },
  bbWidth: { label: "BB Width", kind: "indicator", color: "#FF6D00" },
  bbPercentB: { label: "BB %B", kind: "indicator", color: "#2962FF" },
};
