import type { BollingerSettings, IndicatorPeriods } from "../indicators/advancedIndicatorsTypes";
import type { CompareSeriesSettingsMap } from "../compare-series/compareSeries";
import type { MultiChartLayoutState } from "../layout/multiChartLayoutTypes";
import type { ChartAppearance } from "../state/chartStateTypes";
import type { ActiveMarketState } from "../state/uiStateTypes";

export interface SavedAnalysisIndicators {
  sma: boolean;
  ema: boolean;
  volume: boolean;
  volumeVisible?: boolean;
  activeSma?: number[];
  activeEma?: number[];
  activeWma?: number[];
  activeDema?: number[];
  activeTema?: number[];
  activeHma?: number[];
  activeZlema?: number[];
  activeAlma?: number[];
  activeSmma?: number[];
  activeKama?: number[];
  activeVwma?: number[];
}

export interface SavedAnalysisAdvancedIndicators {
  rsi: boolean;
  macd: boolean;
  bollinger: boolean;
  stochastic: boolean;
  atr: boolean;
  atr20?: boolean;
  natr14?: boolean;
  donchian?: boolean;
  keltner?: boolean;
  hv10?: boolean;
  hv20?: boolean;
  hv30?: boolean;
  hv60?: boolean;
  hv90?: boolean;
  hv252?: boolean;
  stdDev20?: boolean;
  chaikinVol?: boolean;
  cci: boolean;
  cci14?: boolean;
  cci20?: boolean;
  mfi14?: boolean;
  williamsR?: boolean;
  williamsR14?: boolean;
  roc?: boolean;
  roc10?: boolean;
  roc20?: boolean;
  momentum10?: boolean;
  momentum20?: boolean;
  cmo14?: boolean;
  dymi?: boolean;
  ultimateOsc?: boolean;
  dpo20?: boolean;
  tsi?: boolean;
  awesomeOsc?: boolean;
  acOsc?: boolean;
  rvi?: boolean;
  fisherTransform?: boolean;
  elderBullBear?: boolean;
  coppock?: boolean;
  ppo?: boolean;
  apo?: boolean;
  parabolicSar?: boolean;
  kst?: boolean;
  linearRegression?: boolean;
  ulcerIndex?: boolean;
  obv?: boolean;
  adLine?: boolean;
  cmf20?: boolean;
  nvi?: boolean;
  pvi?: boolean;
  chaikinOsc?: boolean;
  volumeOsc?: boolean;
  vroc14?: boolean;
  klinger?: boolean;
  elderForceIndex?: boolean;
  eom14?: boolean;
  volumeProfile?: boolean;
  pivotPointsStandard?: boolean;
  pivotPointsFibonacci?: boolean;
  movingAverageCrosses?: boolean;
  vwap?: boolean;
  fiftyTwoWeekHigh?: boolean;
  fiftyTwoWeekLow?: boolean;
  ath?: boolean;
  atl?: boolean;
  breakoutResistance?: boolean;
  breakdownSupport?: boolean;
  gapUp?: boolean;
  gapDown?: boolean;
  trueGapUp?: boolean;
  trueGapDown?: boolean;
  gapPct?: boolean;
  consecutiveUpDays?: boolean;
  consecutiveDownDays?: boolean;
  insideBar?: boolean;
  outsideBar?: boolean;
  doji?: boolean;
  longLeggedDoji?: boolean;
  rickshawMan?: boolean;
  dragonflyDoji?: boolean;
  gravestoneDoji?: boolean;
  tristar?: boolean;
  hammer?: boolean;
  hangingMan?: boolean;
  takuri?: boolean;
  invertedHammer?: boolean;
  shootingStar?: boolean;
  engulfingBullish?: boolean;
  engulfingBearish?: boolean;
  haramiBullish?: boolean;
  haramiBearish?: boolean;
  tweezerTop?: boolean;
  tweezerBottom?: boolean;
  piercingLine?: boolean;
  darkCloudCover?: boolean;
  tasukiGap?: boolean;
  separatingLines?: boolean;
  thrusting?: boolean;
  counterattack?: boolean;
  morningStar?: boolean;
  eveningStar?: boolean;
  threeWhiteSoldiers?: boolean;
  threeBlackCrows?: boolean;
  threeInsideUp?: boolean;
  threeInsideDown?: boolean;
  uniqueThreeRiver?: boolean;
  upsideGapTwoCrows?: boolean;
  kickerBull?: boolean;
  kickerBear?: boolean;
  abandonedBabyBull?: boolean;
  abandonedBabyBear?: boolean;
  beltHoldBull?: boolean;
  beltHoldBear?: boolean;
  breakawayBull?: boolean;
  breakawayBear?: boolean;
  risingThreeMethods?: boolean;
  fallingThreeMethods?: boolean;
  matHold?: boolean;
  gapSideBySideWhite?: boolean;
  hikkake?: boolean;
  concealingBabySwallow?: boolean;
  ladderBottom?: boolean;
  stickSandwich?: boolean;
  marubozuBull?: boolean;
  marubozuBear?: boolean;
  spinningTop?: boolean;
  ichimoku?: boolean;
  stochRsi?: boolean;
  // [TENOR 2026 HDR] Optional for backward compatibility
  bbWidth?: boolean;
  bbPercentB?: boolean;
}

export interface SavedAnalysis {
  id: string;
  name: string;
  config: {
    /** Schema version for backward-compatible IndexedDB migrations. */
    version?: 2;
    symbol: string;
    timeframe: string;
    chartType: string;
    indicators: SavedAnalysisIndicators;
    advancedIndicators: SavedAnalysisAdvancedIndicators;
    indicatorPeriods?: IndicatorPeriods;
    bollingerSettings?: BollingerSettings;
    chartAppearance?: ChartAppearance;
    multiChartLayout?: MultiChartLayoutState;
    comparisonSymbols?: string[];
    comparisonSettings?: CompareSeriesSettingsMap;
    activeMarket?: ActiveMarketState;
    timeRange?: string;
    savedAt: string;
  };
}

// ============================================================================
// GLOBAL CONFIG TYPES
// ============================================================================
