import React from 'react';
import { TOOL_CATEGORIES } from './TechnicalAnalysisConstants';
import {
    LineIcon,
    HorizontalLineIcon,
    RayIcon,
    TrendAngleIcon,
    ArrowIcon,
    ExtendedLineIcon,
    HorizontalRayIcon,
    PolylineIcon,
    PathIcon,
    CurveIcon,
    CrosshairIcon,
    ArrowMarkerIcon,
    ProjectionIcon,
    DateRangeIcon,
    PriceRangeIcon,
    DatePriceRangeIcon,
    ParallelChannelIcon,
    RegressionTrendIcon,
    DisjointChannelIcon,
    FlatTopBottomIcon,
    FibRetracementIcon,
    FibExtensionIcon,
    FibChannelIcon,
    FibTimeZoneIcon,
    FibSpeedFanIcon,
    FibTimeIcon,
    FibCirclesIcon,
    FibSpiralIcon,
    FibSpeedArcsIcon,
    FibWedgeIcon,
    PitchfanIcon,
    GannBoxIcon,
    GannSquareFixedIcon,
    GannSquareIcon,
    GannFanIcon,
    PitchforkIcon,
    SchiffPitchforkIcon,
    ModifiedSchiffPitchforkIcon,
    InsidePitchforkIcon,
    XABCDPatternIcon,
    CypherPatternIcon,
    HeadAndShouldersIcon,
    ABCDPatternIcon,
    TrianglePatternIcon,
    ThreeDrivesPatternIcon,
    ElliottImpulseIcon,
    ElliottCorrectionIcon,
    ElliottTriangleIcon,
    ElliottDoubleComboIcon,
    ElliottTripleComboIcon,
    CyclicLinesIcon,
    TimeCyclesIcon,
    SineLineIcon,
    ForecastingLongIcon,
    ForecastingShortIcon,
    ForecastingForecastIcon,
    ForecastingBarPatternIcon,
    ForecastingGhostFeedIcon,
    ForecastingSectorIcon,
    AnchoredVWAPIcon,
    AnchoredVolumeProfileIcon,
} from '../components/common/ToolIcons';

export const DRAWING_TOOLS_CONFIG = [
    // Lines & Measures
    { id: "line", label: "Ligne de tendance", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <LineIcon />, },
    { id: "horizontal_line", label: "Ligne horizontale", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <HorizontalLineIcon />, },
    { id: "arrow", label: "Flèche", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <ArrowIcon />, },
    { id: "trend_angle", label: "Angle de tendance", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <TrendAngleIcon />, },
    { id: "ray", label: "Rayon (Demi-droite)", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <RayIcon />, },
    { id: "x_line", label: "Ligne étendue", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <ExtendedLineIcon />, },
    { id: "horizontal_ray", label: "Rayon horizontal", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <HorizontalRayIcon />, },
    { id: "polyline", label: "Polyligne", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <PolylineIcon />, },
    { id: "path", label: "Chemin", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <PathIcon />, },
    { id: "curve", label: "Courbe", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <CurveIcon />, },
    { id: "crosshair", label: "Réticule", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <CrosshairIcon />, },
    { id: "arrow_marker", label: "Marqueur fléché", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <ArrowMarkerIcon />, },
    { id: "projection", label: "Projection", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <ProjectionIcon />, },
    { id: "date_range", label: "Plage de dates", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <DateRangeIcon />, },
    { id: "price_range", label: "Plage de prix", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <PriceRangeIcon />, },
    { id: "date_price_range", label: "Date & Prix", category: TOOL_CATEGORIES.LINES_MEASURES, icon: <DatePriceRangeIcon />, },


    // Channels
    { id: "parallel_channel", label: "Parallel Channel", category: TOOL_CATEGORIES.CHANNELS, icon: <ParallelChannelIcon />, },
    { id: "regression_trend", label: "Regression Trend", category: TOOL_CATEGORIES.CHANNELS, icon: <RegressionTrendIcon />, },
    { id: "disjoint_channel", label: "Disjoint Channel", category: TOOL_CATEGORIES.CHANNELS, icon: <DisjointChannelIcon />, },
    { id: "flat_top_bottom", label: "Flat Top/Bottom", category: TOOL_CATEGORIES.CHANNELS, icon: <FlatTopBottomIcon />, },


    // Gann and Fibonacci Tools
    { id: "fib_retracement", label: "Retracement de Fibonacci", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibRetracementIcon />, },
    { id: "trend_based_fib_extension", label: "Trend-Based Fib Extension", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibExtensionIcon />, },
    { id: "fib_channel", label: "Fib Channel", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibChannelIcon />, },
    { id: "fib_time_zone", label: "Fib Time Zone", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibTimeZoneIcon />, },
    { id: "fib_speed_resistance_fan", label: "Fib Speed Resistance Fan", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibSpeedFanIcon />, },
    { id: "trend_based_fib_time", label: "Trend-Based Fib Time", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibTimeIcon />, },
    { id: "fib_circles", label: "Fib Circles", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibCirclesIcon />, },
    { id: "fib_spiral", label: "Fib Spiral", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibSpiralIcon />, },
    { id: "fib_speed_resistance_arcs", label: "Fib Speed Resistance Arcs", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibSpeedArcsIcon />, },
    { id: "fib_wedge", label: "Fib Wedge", category: TOOL_CATEGORIES.FIBONACCI, icon: <FibWedgeIcon />, },
    { id: "pitchfan", label: "Pitchfan", category: TOOL_CATEGORIES.FIBONACCI, icon: <PitchfanIcon />, },
    { id: "gann_box", label: "Gann Box", category: TOOL_CATEGORIES.FIBONACCI, icon: <GannBoxIcon />, },
    { id: "gann_square_fixed", label: "Gann Square Fixed", category: TOOL_CATEGORIES.FIBONACCI, icon: <GannSquareFixedIcon />, },
    { id: "gann_square", label: "Gann Square", category: TOOL_CATEGORIES.FIBONACCI, icon: <GannSquareIcon />, },
    { id: "gann_fan", label: "Gann Fan", category: TOOL_CATEGORIES.FIBONACCI, icon: <GannFanIcon />, },
    { id: "pitchfork", label: "Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS, icon: <PitchforkIcon />, },
    { id: "schiff_pitchfork", label: "Schiff Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS, icon: <SchiffPitchforkIcon />, },
    { id: "modified_schiff_pitchfork", label: "Modified Schiff Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS, icon: <ModifiedSchiffPitchforkIcon />, },
    { id: "inside_pitchfork", label: "Inside Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS, icon: <InsidePitchforkIcon />, },
  
  
  
    // Chart Patterns
    { id: "xabcd_pattern", label: "XABCD Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <XABCDPatternIcon />, },
    { id: "cypher_pattern", label: "Cypher Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <CypherPatternIcon />, },
    { id: "head_and_shoulders", label: "Head and Shoulders", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <HeadAndShouldersIcon />, },
    { id: "abcd_pattern", label: "ABCD Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <ABCDPatternIcon />, },
    { id: "triangle_pattern", label: "Triangle Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <TrianglePatternIcon />, },
    { id: "three_drives_pattern", label: "Three Drives Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS, icon: <ThreeDrivesPatternIcon />, },


    // Elliott Waves
    { id: "elliott_impulse_wave", label: "Elliott impulse wave (1-2-3-4-5)", category: TOOL_CATEGORIES.ELLIOTT_WAVES, icon: <ElliottImpulseIcon />, },
    { id: "elliott_correction_wave", label: "Elliott correction wave (A-B-C)", category: TOOL_CATEGORIES.ELLIOTT_WAVES, icon: <ElliottCorrectionIcon />, },
    { id: "elliott_triangle_wave", label: "Elliott triangle wave (A-B-C-D-E)", category: TOOL_CATEGORIES.ELLIOTT_WAVES, icon: <ElliottTriangleIcon />, },
    { id: "elliott_double_combo_wave", label: "Elliott double combo wave (W-X-Y)", category: TOOL_CATEGORIES.ELLIOTT_WAVES, icon: <ElliottDoubleComboIcon />, },
    { id: "elliott_triple_combo_wave", label: "Elliott triple combo wave (W-X-Y-X-Z)", category: TOOL_CATEGORIES.ELLIOTT_WAVES, icon: <ElliottTripleComboIcon />, },


    // Cycles
    { id: "cyclic_lines", label: "Cyclic lines", category: TOOL_CATEGORIES.CYCLES, icon: <CyclicLinesIcon />, },
    { id: "time_cycles", label: "Time cycles", category: TOOL_CATEGORIES.CYCLES, icon: <TimeCyclesIcon />, },
    { id: "sine_line", label: "Sine line", category: TOOL_CATEGORIES.CYCLES, icon: <SineLineIcon />, },

    
    // Forecasting
    { id: "long_position", label: "Position Longue", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingLongIcon />, },
    { id: "short_position", label: "Position Courte", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingShortIcon />, },
    { id: "position_forecast", label: "Position Forecast", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingForecastIcon />, },
    { id: "bar_pattern", label: "Bar Pattern", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingBarPatternIcon />, },
    { id: "ghost_feed", label: "Ghost Feed", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingGhostFeedIcon />, },
    { id: "sector", label: "Sector", category: TOOL_CATEGORIES.FORECASTING, icon: <ForecastingSectorIcon />, },
    { id: "anchored_vwap", label: "Anchored VWAP", category: TOOL_CATEGORIES.VOLUME_BASED, icon: <AnchoredVWAPIcon />, },
    { id: "anchored_volume_profile", label: "Fixed Range Volume Profile", category: TOOL_CATEGORIES.VOLUME_BASED, icon: <AnchoredVolumeProfileIcon />, },
];
