import { TOOL_CATEGORIES, type DrawingToolCategory } from "./drawingConstants";
import type { AllToolType } from "./drawingToolTypes";

export type DrawingToolId = NonNullable<AllToolType>;

export interface DrawingToolSpec {
  id: DrawingToolId;
  label: string;
  category: DrawingToolCategory;
}

export const DRAWING_TOOL_SPECS = [
  { id: "line", label: "Ligne de tendance", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "horizontal_line", label: "Ligne horizontale", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "vertical_line", label: "Ligne verticale", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "arrow", label: "Flèche", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "trend_angle", label: "Angle de tendance", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "ray", label: "Rayon (Demi-droite)", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "x_line", label: "Ligne étendue", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "horizontal_ray", label: "Rayon horizontal", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "polyline", label: "Polyligne", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "path", label: "Chemin", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "curve", label: "Courbe", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "crosshair", label: "Réticule", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "arrow_marker", label: "Marqueur fléché", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "projection", label: "Projection", category: TOOL_CATEGORIES.LINES_MEASURES },
  { id: "date_range", label: "Plage de dates", category: TOOL_CATEGORIES.MEASURERS },
  { id: "price_range", label: "Plage de prix", category: TOOL_CATEGORIES.MEASURERS },
  { id: "date_price_range", label: "Date & Prix", category: TOOL_CATEGORIES.MEASURERS },
  { id: "parallel_channel", label: "Parallel Channel", category: TOOL_CATEGORIES.CHANNELS },
  { id: "regression_trend", label: "Regression Trend", category: TOOL_CATEGORIES.CHANNELS },
  { id: "disjoint_channel", label: "Disjoint Channel", category: TOOL_CATEGORIES.CHANNELS },
  { id: "flat_top_bottom", label: "Flat Top/Bottom", category: TOOL_CATEGORIES.CHANNELS },
  { id: "fib_retracement", label: "Retracement de Fibonacci", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "trend_based_fib_extension", label: "Trend-Based Fib Extension", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_channel", label: "Fib Channel", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_time_zone", label: "Fib Time Zone", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_speed_resistance_fan", label: "Fib Speed Resistance Fan", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "trend_based_fib_time", label: "Trend-Based Fib Time", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_circles", label: "Fib Circles", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_spiral", label: "Fib Spiral", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_speed_resistance_arcs", label: "Fib Speed Resistance Arcs", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "fib_wedge", label: "Fib Wedge", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "pitchfan", label: "Pitchfan", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "gann_box", label: "Gann Box", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "gann_square_fixed", label: "Gann Square Fixed", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "gann_square", label: "Gann Square", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "gann_fan", label: "Gann Fan", category: TOOL_CATEGORIES.FIBONACCI },
  { id: "pitchfork", label: "Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS },
  { id: "schiff_pitchfork", label: "Schiff Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS },
  { id: "modified_schiff_pitchfork", label: "Modified Schiff Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS },
  { id: "inside_pitchfork", label: "Inside Pitchfork", category: TOOL_CATEGORIES.PITCHFORKS },
  { id: "xabcd_pattern", label: "XABCD Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "cypher_pattern", label: "Cypher Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "head_and_shoulders", label: "Head and Shoulders", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "abcd_pattern", label: "ABCD Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "triangle_pattern", label: "Triangle Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "three_drives_pattern", label: "Three Drives Pattern", category: TOOL_CATEGORIES.CHART_PATTERNS },
  { id: "elliott_impulse_wave", label: "Elliott impulse wave (1-2-3-4-5)", category: TOOL_CATEGORIES.ELLIOTT_WAVES },
  { id: "elliott_correction_wave", label: "Elliott correction wave (A-B-C)", category: TOOL_CATEGORIES.ELLIOTT_WAVES },
  { id: "elliott_triangle_wave", label: "Elliott triangle wave (A-B-C-D-E)", category: TOOL_CATEGORIES.ELLIOTT_WAVES },
  { id: "elliott_double_combo_wave", label: "Elliott double combo wave (W-X-Y)", category: TOOL_CATEGORIES.ELLIOTT_WAVES },
  { id: "elliott_triple_combo_wave", label: "Elliott triple combo wave (W-X-Y-X-Z)", category: TOOL_CATEGORIES.ELLIOTT_WAVES },
  { id: "cyclic_lines", label: "Cyclic lines", category: TOOL_CATEGORIES.CYCLES },
  { id: "time_cycles", label: "Time cycles", category: TOOL_CATEGORIES.CYCLES },
  { id: "sine_line", label: "Sine line", category: TOOL_CATEGORIES.CYCLES },
  { id: "long_position", label: "Position Longue", category: TOOL_CATEGORIES.FORECASTING },
  { id: "short_position", label: "Position Courte", category: TOOL_CATEGORIES.FORECASTING },
  { id: "position_forecast", label: "Position Forecast", category: TOOL_CATEGORIES.FORECASTING },
  { id: "bar_pattern", label: "Bar Pattern", category: TOOL_CATEGORIES.FORECASTING },
  { id: "ghost_feed", label: "Ghost Feed", category: TOOL_CATEGORIES.FORECASTING },
  { id: "sector", label: "Sector", category: TOOL_CATEGORIES.FORECASTING },
  { id: "anchored_vwap", label: "Anchored VWAP", category: TOOL_CATEGORIES.VOLUME_BASED },
  { id: "fixed_range_volume_profile", label: "Fixed Range Volume Profile", category: TOOL_CATEGORIES.VOLUME_BASED },
  { id: "anchored_volume_profile", label: "Anchored Volume Profile", category: TOOL_CATEGORIES.VOLUME_BASED },
  { id: "brush", label: "Brush (Pinceau)", category: TOOL_CATEGORIES.BRUSH_DRAWING },
  { id: "highlighter", label: "Highlighter (Surligneur)", category: TOOL_CATEGORIES.BRUSH_DRAWING },
] as const satisfies readonly DrawingToolSpec[];
