import React from "react";

import type { AllToolType } from "./drawingToolTypes";
import type { DrawingToolId } from "./drawingToolSpecs";
import {
    FibChannelIcon,
    FibCirclesIcon,
    FibExtensionIcon,
    FibRetracementIcon,
    FibSpeedArcsIcon,
    FibSpeedFanIcon,
    FibSpiralIcon,
    FibTimeIcon,
    FibTimeZoneIcon,
    FibWedgeIcon,
    GannBoxIcon,
    GannFanIcon,
    GannSquareFixedIcon,
    GannSquareIcon,
    InsidePitchforkIcon,
    ModifiedSchiffPitchforkIcon,
    PitchfanIcon,
    PitchforkIcon,
    SchiffPitchforkIcon,
} from "../../components/common/icons/drawing/fibonacci";
import {
    AnchoredVolumeProfileIcon,
    AnchoredVWAPIcon,
    ForecastingBarPatternIcon,
    ForecastingForecastIcon,
    ForecastingGhostFeedIcon,
    ForecastingLongIcon,
    ForecastingSectorIcon,
    ForecastingShortIcon,
} from "../../components/common/icons/drawing/forecasting";
import {
    ABCDPatternIcon,
    CyclicLinesIcon,
    CypherPatternIcon,
    ElliottCorrectionIcon,
    ElliottDoubleComboIcon,
    ElliottImpulseIcon,
    ElliottTriangleIcon,
    ElliottTripleComboIcon,
    HeadAndShouldersIcon,
    SineLineIcon,
    ThreeDrivesPatternIcon,
    TimeCyclesIcon,
    TrianglePatternIcon,
    XABCDPatternIcon,
} from "../../components/common/icons/drawing/patterns";
import {
    ArrowIcon,
    ArrowMarkerIcon,
    CrosshairIcon,
    CurveIcon,
    DatePriceRangeIcon,
    DateRangeIcon,
    DisjointChannelIcon,
    ExtendedLineIcon,
    FlatTopBottomIcon,
    HorizontalLineIcon,
    HorizontalRayIcon,
    LineIcon,
    ParallelChannelIcon,
    PathIcon,
    PolylineIcon,
    PriceRangeIcon,
    ProjectionIcon,
    RayIcon,
    RegressionTrendIcon,
    TrendAngleIcon,
    VerticalLineIcon,
} from "../../components/common/icons/drawing/trend";

export const DRAWING_TOOL_ICON_REGISTRY: Partial<Record<DrawingToolId, React.ReactNode>> = {
  line: <LineIcon />,
  horizontal_line: <HorizontalLineIcon />,
  vertical_line: <VerticalLineIcon />,
  arrow: <ArrowIcon />,
  trend_angle: <TrendAngleIcon />,
  ray: <RayIcon />,
  x_line: <ExtendedLineIcon />,
  horizontal_ray: <HorizontalRayIcon />,
  polyline: <PolylineIcon />,
  path: <PathIcon />,
  curve: <CurveIcon />,
  crosshair: <CrosshairIcon />,
  arrow_marker: <ArrowMarkerIcon />,
  projection: <ProjectionIcon />,
  date_range: <DateRangeIcon />,
  price_range: <PriceRangeIcon />,
  date_price_range: <DatePriceRangeIcon />,
  parallel_channel: <ParallelChannelIcon />,
  regression_trend: <RegressionTrendIcon />,
  disjoint_channel: <DisjointChannelIcon />,
  flat_top_bottom: <FlatTopBottomIcon />,
  fib_retracement: <FibRetracementIcon />,
  trend_based_fib_extension: <FibExtensionIcon />,
  fib_channel: <FibChannelIcon />,
  fib_time_zone: <FibTimeZoneIcon />,
  fib_speed_resistance_fan: <FibSpeedFanIcon />,
  trend_based_fib_time: <FibTimeIcon />,
  fib_circles: <FibCirclesIcon />,
  fib_spiral: <FibSpiralIcon />,
  fib_speed_resistance_arcs: <FibSpeedArcsIcon />,
  fib_wedge: <FibWedgeIcon />,
  pitchfan: <PitchfanIcon />,
  gann_box: <GannBoxIcon />,
  gann_square_fixed: <GannSquareFixedIcon />,
  gann_square: <GannSquareIcon />,
  gann_fan: <GannFanIcon />,
  pitchfork: <PitchforkIcon />,
  schiff_pitchfork: <SchiffPitchforkIcon />,
  modified_schiff_pitchfork: <ModifiedSchiffPitchforkIcon />,
  inside_pitchfork: <InsidePitchforkIcon />,
  xabcd_pattern: <XABCDPatternIcon />,
  cypher_pattern: <CypherPatternIcon />,
  head_and_shoulders: <HeadAndShouldersIcon />,
  abcd_pattern: <ABCDPatternIcon />,
  triangle_pattern: <TrianglePatternIcon />,
  three_drives_pattern: <ThreeDrivesPatternIcon />,
  elliott_impulse_wave: <ElliottImpulseIcon />,
  elliott_correction_wave: <ElliottCorrectionIcon />,
  elliott_triangle_wave: <ElliottTriangleIcon />,
  elliott_double_combo_wave: <ElliottDoubleComboIcon />,
  elliott_triple_combo_wave: <ElliottTripleComboIcon />,
  cyclic_lines: <CyclicLinesIcon />,
  time_cycles: <TimeCyclesIcon />,
  sine_line: <SineLineIcon />,
  long_position: <ForecastingLongIcon />,
  short_position: <ForecastingShortIcon />,
  position_forecast: <ForecastingForecastIcon />,
  bar_pattern: <ForecastingBarPatternIcon />,
  ghost_feed: <ForecastingGhostFeedIcon />,
  sector: <ForecastingSectorIcon />,
  anchored_vwap: <AnchoredVWAPIcon />,
  anchored_volume_profile: <AnchoredVolumeProfileIcon />,
};

export const getDrawingToolIcon = (toolId: AllToolType | null): React.ReactNode | null => {
  if (!toolId) return null;
  return DRAWING_TOOL_ICON_REGISTRY[toolId as DrawingToolId] ?? null;
};
