export type CandlestickPatternKey =
  | "doji"
  | "longLeggedDoji"
  | "rickshawMan"
  | "dragonflyDoji"
  | "gravestoneDoji"
  | "tristar"
  | "hammer"
  | "hangingMan"
  | "takuri"
  | "invertedHammer"
  | "shootingStar"
  | "engulfingBullish"
  | "engulfingBearish"
  | "haramiBullish"
  | "haramiBearish"
  | "tweezerTop"
  | "tweezerBottom"
  | "piercingLine"
  | "darkCloudCover"
  | "tasukiGap"
  | "separatingLines"
  | "thrusting"
  | "counterattack"
  | "morningStar"
  | "eveningStar"
  | "threeWhiteSoldiers"
  | "threeBlackCrows"
  | "threeInsideUp"
  | "threeInsideDown"
  | "uniqueThreeRiver"
  | "upsideGapTwoCrows"
  | "kickerBull"
  | "kickerBear"
  | "abandonedBabyBull"
  | "abandonedBabyBear"
  | "beltHoldBull"
  | "beltHoldBear"
  | "breakawayBull"
  | "breakawayBear"
  | "risingThreeMethods"
  | "fallingThreeMethods"
  | "matHold"
  | "gapSideBySideWhite"
  | "hikkake"
  | "concealingBabySwallow"
  | "ladderBottom"
  | "ladderBottomBrvm"
  | "stickSandwich"
  | "marubozuBull"
  | "marubozuBear"
  | "spinningTop";

type CandlestickMarkerPosition = "above" | "below" | "center";
type CandlestickMarkerSymbol = "circle" | "rect" | "roundRect" | "triangle" | "diamond" | `path://${string}`;
type CandlestickLabelPosition = "top" | "bottom" | "inside";
type CandlestickLabelPadding = number | [number, number] | [number, number, number, number];
type CandlestickLabelFontWeight = number | "normal" | "bold" | "bolder" | "lighter";

export type CandlestickPatternPresentation = {
  markerId: string;
  legendName: string;
  shortLabel?: string;
  chartLabel?: string;
  color: string;
  opacity?: number;
  borderColor: string;
  labelBackgroundColor: string;
  labelTextColor: string;
  labelBorderColor?: string;
  labelBorderWidth?: number;
  labelBorderRadius?: number;
  labelPadding?: CandlestickLabelPadding;
  labelFontSize?: number;
  labelFontWeight?: CandlestickLabelFontWeight;
  labelLineHeight?: number;
  labelDistance?: number;
  verticalBandColor?: string;
  verticalBandWidthRatio?: number;
  verticalBandZ?: number;
  showChartLabel: boolean;
  position: CandlestickMarkerPosition;
  symbol: CandlestickMarkerSymbol;
  symbolSize: number | [number, number];
  symbolOffset: [number, number];
  symbolRotate: number;
  labelPosition: CandlestickLabelPosition;
  maxMarkers: number;
  minBarGap: number;
  z: number;
};

export type CandlestickPatternSignalSummary = {
  legendName: string;
  shortLabel?: string;
  count: number;
};

export const CANDLESTICK_PATTERN_PRIORITY: readonly CandlestickPatternKey[] = [
  "abandonedBabyBull",
  "abandonedBabyBear",
  "kickerBull",
  "kickerBear",
  "breakawayBull",
  "breakawayBear",
  "hikkake",
  "risingThreeMethods",
  "fallingThreeMethods",
  "matHold",
  "concealingBabySwallow",
  "ladderBottom",
  "ladderBottomBrvm",
  "stickSandwich",
  "gapSideBySideWhite",
  "threeInsideUp",
  "threeInsideDown",
  "uniqueThreeRiver",
  "upsideGapTwoCrows",
  "beltHoldBull",
  "beltHoldBear",
  "morningStar",
  "eveningStar",
  "threeWhiteSoldiers",
  "threeBlackCrows",
  "tasukiGap",
  "counterattack",
  "separatingLines",
  "thrusting",
  "tristar",
  "engulfingBullish",
  "engulfingBearish",
  "piercingLine",
  "darkCloudCover",
  "haramiBullish",
  "haramiBearish",
  "tweezerTop",
  "tweezerBottom",
  "takuri",
  "hammer",
  "hangingMan",
  "invertedHammer",
  "shootingStar",
  "marubozuBull",
  "marubozuBear",
  "spinningTop",
  "dragonflyDoji",
  "gravestoneDoji",
  "rickshawMan",
  "longLeggedDoji",
  "doji",
];

const brightText = "#020617";
const lightText = "#f8fafc";

const aboveOffset: [number, number] = [0, -10];
const belowOffset: [number, number] = [0, 10];
const centerOffset: [number, number] = [0, 0];

export const CANDLESTICK_PATTERN_PRESENTATIONS = {
  tristar: {
    markerId: "tristar-zone",
    legendName: "Tristar",
    shortLabel: "TRI",
    color: "#8b5cf6",
    borderColor: "#c4b5fd",
    labelBackgroundColor: "#8b5cf6",
    labelTextColor: lightText,
    showChartLabel: true,
    position: "center",
    symbol: "roundRect",
    symbolSize: [18, 10],
    symbolOffset: centerOffset,
    symbolRotate: 0,
    labelPosition: "inside",
    maxMarkers: 18,
    minBarGap: 2,
    z: 34,
  },
  takuri: {
    markerId: "takuri-marker",
    legendName: "Takuri",
    shortLabel: "TK",
    color: "#14b8a6",
    borderColor: "#99f6e4",
    labelBackgroundColor: "#14b8a6",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "below",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 36,
    minBarGap: 1,
    z: 35,
  },
  hammer: {
    markerId: "hammer-marker",
    legendName: "Hammer",
    shortLabel: "H",
    color: "#22c55e",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "#22c55e",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "below",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 36,
    minBarGap: 1,
    z: 35,
  },
  hangingMan: {
    markerId: "hanging-man-marker",
    legendName: "Hanging Man",
    shortLabel: "HM",
    color: "#f97316",
    borderColor: "#fed7aa",
    labelBackgroundColor: "#f97316",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "above",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 36,
    minBarGap: 1,
    z: 35,
  },
  invertedHammer: {
    markerId: "inverted-hammer-marker",
    legendName: "Inverted Hammer",
    shortLabel: "IH",
    color: "#38bdf8",
    borderColor: "#bae6fd",
    labelBackgroundColor: "#38bdf8",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "below",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 36,
    minBarGap: 1,
    z: 35,
  },
  shootingStar: {
    markerId: "shooting-star-marker",
    legendName: "Shooting Star",
    shortLabel: "SS-",
    color: "#be123c",
    borderColor: "#fecdd3",
    labelBackgroundColor: "rgba(190, 18, 60, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 205, 211, 0.9)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    showChartLabel: true,
    position: "above",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 18,
    minBarGap: 3,
    z: 38,
  },
  engulfingBullish: {
    markerId: "engulfing-bullish-bracket",
    legendName: "Engulfing Bullish",
    shortLabel: "ENG+",
    color: "#16a34a",
    borderColor: "#86efac",
    labelBackgroundColor: "rgba(22, 163, 74, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(187, 247, 208, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [22, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 18,
    minBarGap: 3,
    z: 39,
  },
  engulfingBearish: {
    markerId: "engulfing-bearish-bracket",
    legendName: "Engulfing Bearish",
    shortLabel: "ENG-",
    color: "#dc2626",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(220, 38, 38, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [22, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 18,
    minBarGap: 3,
    z: 39,
  },
  haramiBullish: {
    markerId: "harami-bullish-bracket",
    legendName: "Harami Bullish",
    shortLabel: "HAR+",
    color: "#0ea5e9",
    borderColor: "#bae6fd",
    labelBackgroundColor: "rgba(14, 165, 233, 0.92)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(186, 230, 253, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [21, 9],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 16,
    minBarGap: 3,
    z: 36,
  },
  haramiBearish: {
    markerId: "harami-bearish-bracket",
    legendName: "Harami Bearish",
    shortLabel: "HAR-",
    color: "#f97316",
    borderColor: "#fed7aa",
    labelBackgroundColor: "rgba(249, 115, 22, 0.92)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(254, 215, 170, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [21, 9],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 16,
    minBarGap: 3,
    z: 36,
  },
  tweezerTop: {
    markerId: "tweezer-top-line",
    legendName: "Tweezer Top",
    shortLabel: "TW-",
    color: "#e11d48",
    borderColor: "#fda4af",
    labelBackgroundColor: "rgba(225, 29, 72, 0.92)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(253, 164, 175, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "above",
    symbol: "rect",
    symbolSize: [18, 8],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 14,
    minBarGap: 3,
    z: 35,
  },
  tweezerBottom: {
    markerId: "tweezer-bottom-line",
    legendName: "Tweezer Bottom",
    shortLabel: "TW+",
    color: "#0891b2",
    borderColor: "#67e8f9",
    labelBackgroundColor: "rgba(8, 145, 178, 0.92)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(103, 232, 249, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "rect",
    symbolSize: [18, 8],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 14,
    minBarGap: 3,
    z: 35,
  },
  piercingLine: {
    markerId: "piercing-line-marker",
    legendName: "Piercing Line",
    shortLabel: "PLC",
    color: "#22c55e",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "rgba(34, 197, 94, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(187, 247, 208, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    showChartLabel: true,
    position: "below",
    symbol: "triangle",
    symbolSize: 8,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 16,
    minBarGap: 3,
    z: 38,
  },
  darkCloudCover: {
    markerId: "dark-cloud-cover-marker",
    legendName: "Dark Cloud Cover",
    shortLabel: "DCC",
    color: "#b91c1c",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(185, 28, 28, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    showChartLabel: true,
    position: "above",
    symbol: "triangle",
    symbolSize: 8,
    symbolOffset: aboveOffset,
    symbolRotate: 180,
    labelPosition: "top",
    maxMarkers: 16,
    minBarGap: 3,
    z: 38,
  },
  tasukiGap: {
    markerId: "tasuki-gap-bracket",
    legendName: "Tasuki Gap",
    shortLabel: "TSK",
    color: "#22c55e",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "rgba(22, 163, 74, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(187, 247, 208, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(34, 197, 94, 0.07)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [22, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 14,
    minBarGap: 3,
    z: 40,
  },
  separatingLines: {
    markerId: "separating-lines-marker",
    legendName: "Separating Lines",
    shortLabel: "SEP",
    color: "#38bdf8",
    borderColor: "#bae6fd",
    labelBackgroundColor: "rgba(14, 165, 233, 0.92)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(186, 230, 253, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [20, 9],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 16,
    minBarGap: 3,
    z: 36,
  },
  thrusting: {
    markerId: "thrusting-marker",
    legendName: "Thrusting",
    shortLabel: "THR",
    color: "#f97316",
    borderColor: "#fed7aa",
    labelBackgroundColor: "rgba(249, 115, 22, 0.92)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(254, 215, 170, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "above",
    symbol: "triangle",
    symbolSize: 8,
    symbolOffset: aboveOffset,
    symbolRotate: 180,
    labelPosition: "top",
    maxMarkers: 16,
    minBarGap: 3,
    z: 35,
  },
  counterattack: {
    markerId: "counterattack-bracket",
    legendName: "Counterattack",
    shortLabel: "CTA",
    color: "#a855f7",
    borderColor: "#e9d5ff",
    labelBackgroundColor: "rgba(168, 85, 247, 0.92)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(233, 213, 255, 0.78)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "diamond",
    symbolSize: 8,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 16,
    minBarGap: 3,
    z: 37,
  },
  morningStar: {
    markerId: "morning-star-bracket",
    legendName: "Morning Star",
    shortLabel: "MS",
    color: "#10b981",
    borderColor: "#a7f3d0",
    labelBackgroundColor: "rgba(16, 185, 129, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(167, 243, 208, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(16, 185, 129, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [20, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 12,
    minBarGap: 4,
    z: 43,
  },
  eveningStar: {
    markerId: "evening-star-bracket",
    legendName: "Evening Star",
    shortLabel: "ES",
    color: "#ef4444",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(239, 68, 68, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(239, 68, 68, 0.08)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [20, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 12,
    minBarGap: 4,
    z: 43,
  },
  threeWhiteSoldiers: {
    markerId: "three-white-soldiers-bracket",
    legendName: "Three White Soldiers",
    shortLabel: "3WS",
    color: "#65a30d",
    borderColor: "#d9f99d",
    labelBackgroundColor: "rgba(101, 163, 13, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(217, 249, 157, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(101, 163, 13, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [24, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 12,
    minBarGap: 4,
    z: 42,
  },
  threeBlackCrows: {
    markerId: "three-black-crows-bracket",
    legendName: "Three Black Crows",
    shortLabel: "3BC",
    color: "#991b1b",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(153, 27, 27, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(153, 27, 27, 0.08)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [24, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 12,
    minBarGap: 4,
    z: 42,
  },
  threeInsideUp: {
    markerId: "three-inside-up-bracket",
    legendName: "Three Inside Up",
    shortLabel: "3IU",
    color: "#22c55e",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "rgba(34, 197, 94, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(187, 247, 208, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(34, 197, 94, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [24, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 12,
    minBarGap: 4,
    z: 44,
  },
  threeInsideDown: {
    markerId: "three-inside-down-bracket",
    legendName: "Three Inside Down",
    shortLabel: "3ID",
    color: "#dc2626",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(220, 38, 38, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(220, 38, 38, 0.08)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [24, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 12,
    minBarGap: 4,
    z: 44,
  },
  uniqueThreeRiver: {
    markerId: "unique-three-river-bracket",
    legendName: "Unique Three River",
    shortLabel: "U3R",
    color: "#14b8a6",
    borderColor: "#99f6e4",
    labelBackgroundColor: "rgba(20, 184, 166, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(153, 246, 228, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(20, 184, 166, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "diamond",
    symbolSize: 9,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 10,
    minBarGap: 4,
    z: 43,
  },
  upsideGapTwoCrows: {
    markerId: "upside-gap-two-crows-bracket",
    legendName: "Upside Gap Two Crows",
    shortLabel: "U2C",
    color: "#b91c1c",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(185, 28, 28, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(185, 28, 28, 0.08)",
    showChartLabel: true,
    position: "above",
    symbol: "diamond",
    symbolSize: 9,
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 10,
    minBarGap: 4,
    z: 43,
  },
  kickerBull: {
    markerId: "kicker-bull-bracket",
    legendName: "Kicker Bull",
    shortLabel: "KB+",
    color: "#16a34a",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "rgba(22, 163, 74, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(187, 247, 208, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(22, 163, 74, 0.09)",
    showChartLabel: true,
    position: "below",
    symbol: "triangle",
    symbolSize: 9,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 10,
    minBarGap: 4,
    z: 45,
  },
  kickerBear: {
    markerId: "kicker-bear-bracket",
    legendName: "Kicker Bear",
    shortLabel: "KB-",
    color: "#ef4444",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(239, 68, 68, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(239, 68, 68, 0.09)",
    showChartLabel: true,
    position: "above",
    symbol: "triangle",
    symbolSize: 9,
    symbolOffset: aboveOffset,
    symbolRotate: 180,
    labelPosition: "top",
    maxMarkers: 10,
    minBarGap: 4,
    z: 45,
  },
  abandonedBabyBull: {
    markerId: "abandoned-baby-bull-bracket",
    legendName: "Abandoned Baby Bull",
    shortLabel: "ABB+",
    color: "#0d9488",
    borderColor: "#99f6e4",
    labelBackgroundColor: "rgba(13, 148, 136, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(153, 246, 228, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(13, 148, 136, 0.10)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [25, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 46,
  },
  abandonedBabyBear: {
    markerId: "abandoned-baby-bear-bracket",
    legendName: "Abandoned Baby Bear",
    shortLabel: "ABB-",
    color: "#e11d48",
    borderColor: "#fda4af",
    labelBackgroundColor: "rgba(225, 29, 72, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(253, 164, 175, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(225, 29, 72, 0.10)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [25, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 8,
    minBarGap: 5,
    z: 46,
  },
  beltHoldBull: {
    markerId: "belt-hold-bull-marker",
    legendName: "Belt Hold Bull",
    shortLabel: "BH+",
    color: "#84cc16",
    borderColor: "#d9f99d",
    labelBackgroundColor: "rgba(132, 204, 22, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(217, 249, 157, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "rect",
    symbolSize: [18, 8],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 18,
    minBarGap: 3,
    z: 41,
  },
  beltHoldBear: {
    markerId: "belt-hold-bear-marker",
    legendName: "Belt Hold Bear",
    shortLabel: "BH-",
    color: "#f97316",
    borderColor: "#fed7aa",
    labelBackgroundColor: "rgba(249, 115, 22, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(254, 215, 170, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "above",
    symbol: "rect",
    symbolSize: [18, 8],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 18,
    minBarGap: 3,
    z: 41,
  },
  breakawayBull: {
    markerId: "breakaway-bull-bracket",
    legendName: "Breakaway Bull",
    shortLabel: "BRK+",
    color: "#10b981",
    borderColor: "#a7f3d0",
    labelBackgroundColor: "rgba(16, 185, 129, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(167, 243, 208, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 8,
    verticalBandColor: "rgba(16, 185, 129, 0.10)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [28, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 6,
    minBarGap: 6,
    z: 45,
  },
  breakawayBear: {
    markerId: "breakaway-bear-bracket",
    legendName: "Breakaway Bear",
    shortLabel: "BRK-",
    color: "#7f1d1d",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(127, 29, 29, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 8,
    verticalBandColor: "rgba(127, 29, 29, 0.10)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [28, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 6,
    minBarGap: 6,
    z: 45,
  },
  risingThreeMethods: {
    markerId: "rising-three-methods-bracket",
    legendName: "Rising Three Methods",
    shortLabel: "R3M",
    color: "#15803d",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "rgba(21, 128, 61, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(187, 247, 208, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 8,
    verticalBandColor: "rgba(21, 128, 61, 0.09)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [28, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 44,
  },
  fallingThreeMethods: {
    markerId: "falling-three-methods-bracket",
    legendName: "Falling Three Methods",
    shortLabel: "F3M",
    color: "#b91c1c",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(185, 28, 28, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 202, 202, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 8,
    verticalBandColor: "rgba(185, 28, 28, 0.09)",
    showChartLabel: true,
    position: "above",
    symbol: "roundRect",
    symbolSize: [28, 10],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 8,
    minBarGap: 5,
    z: 44,
  },
  matHold: {
    markerId: "mat-hold-bracket",
    legendName: "Mat Hold",
    shortLabel: "MTH",
    color: "#0f766e",
    borderColor: "#99f6e4",
    labelBackgroundColor: "rgba(15, 118, 110, 0.95)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(153, 246, 228, 0.86)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 8,
    verticalBandColor: "rgba(20, 184, 166, 0.09)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [27, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 43,
  },
  gapSideBySideWhite: {
    markerId: "gap-side-by-side-white-bracket",
    legendName: "Gap Side-by-Side White",
    shortLabel: "GSS",
    color: "#d97706",
    borderColor: "#fed7aa",
    labelBackgroundColor: "rgba(217, 119, 6, 0.94)",
    labelTextColor: brightText,
    labelBorderColor: "rgba(254, 215, 170, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(217, 119, 6, 0.07)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [26, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 10,
    minBarGap: 4,
    z: 40,
  },
  hikkake: {
    markerId: "hikkake-bracket",
    legendName: "Hikkake",
    shortLabel: "HIK",
    color: "#7c3aed",
    borderColor: "#ddd6fe",
    labelBackgroundColor: "rgba(124, 58, 237, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(221, 214, 254, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(124, 58, 237, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "diamond",
    symbolSize: 9,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 12,
    minBarGap: 3,
    z: 47,
  },
  concealingBabySwallow: {
    markerId: "concealing-baby-swallow-bracket",
    legendName: "Concealing Baby Swallow",
    shortLabel: "CBS",
    color: "#0891b2",
    borderColor: "#67e8f9",
    labelBackgroundColor: "rgba(8, 145, 178, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(103, 232, 249, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(8, 145, 178, 0.09)",
    showChartLabel: true,
    position: "below",
    symbol: "diamond",
    symbolSize: 9,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 43,
  },
  ladderBottom: {
    markerId: "ladder-bottom-bracket",
    legendName: "Ladder Bottom",
    shortLabel: "LDB",
    color: "#65a30d",
    borderColor: "#d9f99d",
    labelBackgroundColor: "rgba(101, 163, 13, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(217, 249, 157, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(101, 163, 13, 0.08)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [27, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 42,
  },
  ladderBottomBrvm: {
    markerId: "ladder-bottom-brvm-bracket",
    legendName: "Ladder Bottom BRVM",
    shortLabel: "LDB-B",
    color: "#84cc16",
    borderColor: "#ecfccb",
    labelBackgroundColor: "rgba(77, 124, 15, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(217, 249, 157, 0.72)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 7,
    verticalBandColor: "rgba(132, 204, 22, 0.07)",
    showChartLabel: true,
    position: "below",
    symbol: "roundRect",
    symbolSize: [34, 10],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 8,
    minBarGap: 5,
    z: 41,
  },
  stickSandwich: {
    markerId: "stick-sandwich-bracket",
    legendName: "Stick Sandwich",
    shortLabel: "SSW",
    color: "#b45309",
    borderColor: "#fed7aa",
    labelBackgroundColor: "rgba(180, 83, 9, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(254, 215, 170, 0.82)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 6,
    verticalBandColor: "rgba(180, 83, 9, 0.07)",
    showChartLabel: true,
    position: "below",
    symbol: "rect",
    symbolSize: [22, 8],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 10,
    minBarGap: 4,
    z: 41,
  },
  marubozuBull: {
    markerId: "marubozu-bull-outline",
    legendName: "Marubozu haussier",
    shortLabel: "MB+",
    color: "#2563eb",
    borderColor: "#93c5fd",
    labelBackgroundColor: "rgba(37, 99, 235, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(248, 250, 252, 0.72)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "below",
    symbol: "rect",
    symbolSize: [14, 8],
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 24,
    minBarGap: 2,
    z: 37,
  },
  marubozuBear: {
    markerId: "marubozu-bear-outline",
    legendName: "Marubozu baissier",
    shortLabel: "MB-",
    color: "#dc2626",
    borderColor: "#fecaca",
    labelBackgroundColor: "rgba(220, 38, 38, 0.94)",
    labelTextColor: lightText,
    labelBorderColor: "rgba(248, 250, 252, 0.72)",
    labelBorderWidth: 1,
    labelBorderRadius: 3,
    labelPadding: [2, 5],
    labelFontSize: 9,
    labelFontWeight: 800,
    labelLineHeight: 11,
    labelDistance: 5,
    showChartLabel: true,
    position: "above",
    symbol: "rect",
    symbolSize: [14, 8],
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 24,
    minBarGap: 2,
    z: 37,
  },
  spinningTop: {
    markerId: "spinning-top-marker",
    legendName: "Spinning Top",
    shortLabel: "ST",
    chartLabel: "ST",
    color: "#facc15",
    opacity: 0.92,
    borderColor: "#facc15",
    labelBackgroundColor: "transparent",
    labelTextColor: "#818cf8",
    labelBorderColor: "transparent",
    labelBorderWidth: 0,
    labelBorderRadius: 0,
    labelPadding: 0,
    labelFontSize: 10,
    labelFontWeight: 500,
    labelLineHeight: 11,
    labelDistance: 2,
    verticalBandColor: "rgba(148, 163, 184, 0.10)",
    verticalBandWidthRatio: 0.62,
    verticalBandZ: 1,
    showChartLabel: true,
    position: "above",
    symbol: "path://M-5 -1.25 L-1.25 -1.25 L-1.25 -5 L1.25 -5 L1.25 -1.25 L5 -1.25 L5 1.25 L1.25 1.25 L1.25 5 L-1.25 5 L-1.25 1.25 L-5 1.25 Z",
    symbolSize: 5,
    symbolOffset: [0, -2],
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 24,
    minBarGap: 3,
    z: 36,
  },
  dragonflyDoji: {
    markerId: "dragonfly-doji-marker",
    legendName: "Dragonfly Doji",
    shortLabel: "DF",
    color: "#22c55e",
    borderColor: "#bbf7d0",
    labelBackgroundColor: "#22c55e",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "below",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: belowOffset,
    symbolRotate: 0,
    labelPosition: "bottom",
    maxMarkers: 24,
    minBarGap: 2,
    z: 35,
  },
  gravestoneDoji: {
    markerId: "gravestone-doji-marker",
    legendName: "Gravestone Doji",
    shortLabel: "GS",
    color: "#f43f5e",
    borderColor: "#fecdd3",
    labelBackgroundColor: "#f43f5e",
    labelTextColor: lightText,
    showChartLabel: true,
    position: "above",
    symbol: "circle",
    symbolSize: 4,
    symbolOffset: aboveOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 24,
    minBarGap: 2,
    z: 35,
  },
  rickshawMan: {
    markerId: "rickshaw-man-marker",
    legendName: "Rickshaw Man",
    shortLabel: "R",
    color: "#c084fc",
    borderColor: "#e9d5ff",
    labelBackgroundColor: "#c084fc",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "center",
    symbol: "diamond",
    symbolSize: 6,
    symbolOffset: centerOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 18,
    minBarGap: 3,
    z: 34,
  },
  longLeggedDoji: {
    markerId: "long-legged-doji-marker",
    legendName: "Long-legged Doji",
    shortLabel: "LL",
    color: "#fbbf24",
    borderColor: "#fde68a",
    labelBackgroundColor: "#fbbf24",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "center",
    symbol: "diamond",
    symbolSize: 6,
    symbolOffset: centerOffset,
    symbolRotate: 0,
    labelPosition: "top",
    maxMarkers: 18,
    minBarGap: 3,
    z: 34,
  },
  doji: {
    markerId: "doji-marker",
    legendName: "Doji",
    color: "#cbd5e1",
    borderColor: "#e2e8f0",
    labelBackgroundColor: "#cbd5e1",
    labelTextColor: brightText,
    showChartLabel: true,
    position: "center",
    symbol: "circle",
    symbolSize: 5,
    symbolOffset: centerOffset,
    symbolRotate: 0,
    labelPosition: "inside",
    maxMarkers: 18,
    minBarGap: 3,
    z: 33,
  },
} satisfies Record<CandlestickPatternKey, CandlestickPatternPresentation>;

export const getCandlestickPatternPresentation = (
  pattern: CandlestickPatternKey,
): CandlestickPatternPresentation => CANDLESTICK_PATTERN_PRESENTATIONS[pattern];

export const buildCandlestickPatternSignalSummary = (
  items: readonly CandlestickPatternSignalSummary[],
  maxItems = 3,
): string | null => {
  const visibleItems = items.filter((item) => item.count > 0);
  if (visibleItems.length === 0) return null;

  const labels = visibleItems.slice(0, maxItems).map((item) => {
    const signalLabel = item.count > 1 ? `${item.count} signaux` : "1 signal";
    const prefix = item.shortLabel ? `${item.shortLabel} ` : "";
    return `${prefix}${item.legendName}: ${signalLabel}`;
  });
  const overflowCount = visibleItems.length - labels.length;

  return `Patterns chandeliers: ${labels.join(" · ")}${overflowCount > 0 ? ` · +${overflowCount}` : ""}`;
};
