import type { AdvancedIndicatorsState } from "./advancedIndicatorsTypes";

export type AdvancedIndicatorId = keyof AdvancedIndicatorsState;
export type IndicatorPanelPlacement = "price-overlay" | "bottom-panel";
export type IndicatorObjectTreeKind = "overlay" | "indicator";

export type IndicatorChildRegistryEntry = {
  id: string;
  label: string;
  kind: IndicatorObjectTreeKind;
  color: string;
};

export type IndicatorFormulaContract = {
  source: "TechnicalIndicators.ts";
  functions: readonly string[];
};

export type IndicatorRendererContract = {
  source: "useEChartsRenderer.ts";
  target: IndicatorPanelPlacement;
  objectTreeIds: readonly string[];
};

export type AdvancedIndicatorRegistryEntry = {
  id: AdvancedIndicatorId;
  key: string;
  label: string;
  stateId: AdvancedIndicatorId;
  panel: IndicatorPanelPlacement;
  kind: IndicatorObjectTreeKind;
  color: string;
  catalogKeys: readonly string[];
  formula: IndicatorFormulaContract;
  renderer: IndicatorRendererContract;
  objectTreeIds: readonly string[];
  children: readonly IndicatorChildRegistryEntry[];
};

const defineIndicatorRegistry = <T extends Record<AdvancedIndicatorId, AdvancedIndicatorRegistryEntry>>(registry: T): T => registry;

export const ADVANCED_INDICATOR_REGISTRY = defineIndicatorRegistry({
  rsi: {"id":"rsi","key":"rsi_9","label":"RSI","stateId":"rsi","panel":"bottom-panel","kind":"indicator","color":"#7E57C2","catalogKeys":["rsi_9","rsi_14","rsi_25"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateRSI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["rsi"]},"objectTreeIds":["rsi"],"children":[]},
  macd: {"id":"macd","key":"macd_line","label":"MACD","stateId":"macd","panel":"bottom-panel","kind":"indicator","color":"#FF9F04","catalogKeys":["macd_line","macd_signal","macd_histogram"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMACD"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["macd","macd-line","macd-signal","macd-hist"]},"objectTreeIds":["macd","macd-line","macd-signal","macd-hist"],"children":[{"id":"macd-line","label":"MACD Line","kind":"indicator","color":"#ffffff"},{"id":"macd-signal","label":"MACD Signal","kind":"indicator","color":"#FF9F04"},{"id":"macd-hist","label":"MACD Histogram","kind":"indicator","color":"#22c55e"}]},
  bollinger: {"id":"bollinger","key":"bb_upper","label":"Bollinger Bands","stateId":"bollinger","panel":"price-overlay","kind":"overlay","color":"#2962FF","catalogKeys":["bb_upper","bb_middle","bb_lower"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateBollinger"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["bollinger","boll-upper","boll-mid","boll-lower","boll-fill","bollinger-fill"]},"objectTreeIds":["bollinger","boll-upper","boll-mid","boll-lower","boll-fill","bollinger-fill"],"children":[{"id":"boll-upper","label":"BB Upper","kind":"overlay","color":"#2962FF"},{"id":"boll-mid","label":"BB Middle","kind":"overlay","color":"#90caf9"},{"id":"boll-lower","label":"BB Lower","kind":"overlay","color":"#2962FF"},{"id":"boll-fill","label":"BB Background","kind":"overlay","color":"#2962FF"}]},
  stochastic: {"id":"stochastic","key":"stoch_k","label":"Stochastic","stateId":"stochastic","panel":"bottom-panel","kind":"indicator","color":"#2962FF","catalogKeys":["stoch_k","stoch_d"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateStochastic"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["stochastic","stoch-k","stoch-d"]},"objectTreeIds":["stochastic","stoch-k","stoch-d"],"children":[{"id":"stoch-k","label":"Stoch %K","kind":"indicator","color":"#2962FF"},{"id":"stoch-d","label":"Stoch %D","kind":"indicator","color":"#FF6D00"}]},
  atr: {"id":"atr","key":"atr_14","label":"ATR 14","stateId":"atr","panel":"bottom-panel","kind":"indicator","color":"#d50000","catalogKeys":["atr_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateATR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["atr"]},"objectTreeIds":["atr"],"children":[]},
  atr20: {"id":"atr20","key":"atr_20","label":"ATR 20","stateId":"atr20","panel":"bottom-panel","kind":"indicator","color":"#fb7185","catalogKeys":["atr_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateATR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["atr20"]},"objectTreeIds":["atr20"],"children":[]},
  natr14: {"id":"natr14","key":"natr_14","label":"NATR 14","stateId":"natr14","panel":"bottom-panel","kind":"indicator","color":"#22c55e","catalogKeys":["natr_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateNATR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["natr14"]},"objectTreeIds":["natr14"],"children":[]},
  donchian: {"id":"donchian","key":"donchian_upper","label":"Donchian Channels","stateId":"donchian","panel":"price-overlay","kind":"overlay","color":"#06b6d4","catalogKeys":["donchian_upper","donchian_middle","donchian_lower"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateDonchianChannels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["donchian","donchian-upper","donchian-middle","donchian-lower","donchian-fill"]},"objectTreeIds":["donchian","donchian-upper","donchian-middle","donchian-lower","donchian-fill"],"children":[{"id":"donchian-upper","label":"Donchian Upper","kind":"overlay","color":"#06b6d4"},{"id":"donchian-middle","label":"Donchian Middle","kind":"overlay","color":"#67e8f9"},{"id":"donchian-lower","label":"Donchian Lower","kind":"overlay","color":"#06b6d4"},{"id":"donchian-fill","label":"Donchian Background","kind":"overlay","color":"#06b6d4"}]},
  keltner: {"id":"keltner","key":"keltner_upper","label":"Keltner Channels","stateId":"keltner","panel":"price-overlay","kind":"overlay","color":"#f59e0b","catalogKeys":["keltner_upper","keltner_middle","keltner_lower"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateKeltnerChannels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["keltner","keltner-upper","keltner-middle","keltner-lower","keltner-fill"]},"objectTreeIds":["keltner","keltner-upper","keltner-middle","keltner-lower","keltner-fill"],"children":[{"id":"keltner-upper","label":"Keltner Upper","kind":"overlay","color":"#f59e0b"},{"id":"keltner-middle","label":"Keltner Middle","kind":"overlay","color":"#fbbf24"},{"id":"keltner-lower","label":"Keltner Lower","kind":"overlay","color":"#f59e0b"},{"id":"keltner-fill","label":"Keltner Background","kind":"overlay","color":"#f59e0b"}]},
  hv10: {"id":"hv10","key":"hv_10","label":"HV 10","stateId":"hv10","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["hv_10"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv10"]},"objectTreeIds":["hv10"],"children":[]},
  hv20: {"id":"hv20","key":"hv_20","label":"HV 20","stateId":"hv20","panel":"bottom-panel","kind":"indicator","color":"#22c55e","catalogKeys":["hv_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv20"]},"objectTreeIds":["hv20"],"children":[]},
  hv30: {"id":"hv30","key":"hv_30","label":"HV 30","stateId":"hv30","panel":"bottom-panel","kind":"indicator","color":"#f59e0b","catalogKeys":["hv_30"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv30"]},"objectTreeIds":["hv30"],"children":[]},
  hv60: {"id":"hv60","key":"hv_60","label":"HV 60","stateId":"hv60","panel":"bottom-panel","kind":"indicator","color":"#a78bfa","catalogKeys":["hv_60"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv60"]},"objectTreeIds":["hv60"],"children":[]},
  hv90: {"id":"hv90","key":"hv_90","label":"HV 90","stateId":"hv90","panel":"bottom-panel","kind":"indicator","color":"#fb7185","catalogKeys":["hv_90"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv90"]},"objectTreeIds":["hv90"],"children":[]},
  hv252: {"id":"hv252","key":"hv_252","label":"HV 252","stateId":"hv252","panel":"bottom-panel","kind":"indicator","color":"#eab308","catalogKeys":["hv_252"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["hv252"]},"objectTreeIds":["hv252"],"children":[]},
  stdDev20: {"id":"stdDev20","key":"std_dev_20","label":"Std Dev 20","stateId":"stdDev20","panel":"bottom-panel","kind":"indicator","color":"#14b8a6","catalogKeys":["std_dev_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceStdDev"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["stdDev20"]},"objectTreeIds":["stdDev20"],"children":[]},
  chaikinVol: {"id":"chaikinVol","key":"chaikin_vol","label":"Chaikin Volatility","stateId":"chaikinVol","panel":"bottom-panel","kind":"indicator","color":"#f97316","catalogKeys":["chaikin_vol"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateChaikinVolatility"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["chaikinVol"]},"objectTreeIds":["chaikinVol"],"children":[]},
  cci: {"id":"cci","key":"cci_20","label":"CCI 20","stateId":"cci","panel":"bottom-panel","kind":"indicator","color":"#00E676","catalogKeys":["cci_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCCI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["cci","cci20"]},"objectTreeIds":["cci","cci20"],"children":[]},
  cci14: {"id":"cci14","key":"cci_14","label":"CCI 14","stateId":"cci14","panel":"bottom-panel","kind":"indicator","color":"#f59e0b","catalogKeys":["cci_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCCI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["cci14"]},"objectTreeIds":["cci14"],"children":[]},
  cci20: {"id":"cci20","key":"cci_20","label":"CCI 20","stateId":"cci20","panel":"bottom-panel","kind":"indicator","color":"#00E676","catalogKeys":["cci_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCCI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["cci20","cci"]},"objectTreeIds":["cci20","cci"],"children":[]},
  mfi14: {"id":"mfi14","key":"mfi_14","label":"MFI 14","stateId":"mfi14","panel":"bottom-panel","kind":"indicator","color":"#10b981","catalogKeys":["mfi_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMFI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["mfi14"]},"objectTreeIds":["mfi14"],"children":[]},
  williamsR: {"id":"williamsR","key":"williams_r_14","label":"Williams %R 14","stateId":"williamsR","panel":"bottom-panel","kind":"indicator","color":"#FFEB3B","catalogKeys":["williams_r_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateWilliamsR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["williamsR","williamsR14"]},"objectTreeIds":["williamsR","williamsR14"],"children":[]},
  williamsR14: {"id":"williamsR14","key":"williams_r_14","label":"Williams %R 14","stateId":"williamsR14","panel":"bottom-panel","kind":"indicator","color":"#FFEB3B","catalogKeys":["williams_r_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateWilliamsR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["williamsR14","williamsR"]},"objectTreeIds":["williamsR14","williamsR"],"children":[]},
  roc: {"id":"roc","key":"roc_10","label":"ROC 10","stateId":"roc","panel":"bottom-panel","kind":"indicator","color":"#2196F3","catalogKeys":["roc_10"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateROC"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["roc","roc10"]},"objectTreeIds":["roc","roc10"],"children":[]},
  roc10: {"id":"roc10","key":"roc_10","label":"ROC 10","stateId":"roc10","panel":"bottom-panel","kind":"indicator","color":"#2196F3","catalogKeys":["roc_10"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateROC"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["roc10","roc"]},"objectTreeIds":["roc10","roc"],"children":[]},
  roc20: {"id":"roc20","key":"roc_20","label":"ROC 20","stateId":"roc20","panel":"bottom-panel","kind":"indicator","color":"#38BDF8","catalogKeys":["roc_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateROC"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["roc20"]},"objectTreeIds":["roc20"],"children":[]},
  momentum10: {"id":"momentum10","key":"momentum_10","label":"Momentum 10","stateId":"momentum10","panel":"bottom-panel","kind":"indicator","color":"#FF2E93","catalogKeys":["momentum_10"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMomentum"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["momentum10"]},"objectTreeIds":["momentum10"],"children":[]},
  momentum20: {"id":"momentum20","key":"momentum_20","label":"Momentum 20","stateId":"momentum20","panel":"bottom-panel","kind":"indicator","color":"#F97316","catalogKeys":["momentum_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMomentum"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["momentum20"]},"objectTreeIds":["momentum20"],"children":[]},
  cmo14: {"id":"cmo14","key":"cmo_14","label":"CMO 14","stateId":"cmo14","panel":"bottom-panel","kind":"indicator","color":"#FB7185","catalogKeys":["cmo_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCMO"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["cmo14"]},"objectTreeIds":["cmo14"],"children":[]},
  dymi: {"id":"dymi","key":"dymi","label":"DYMI","stateId":"dymi","panel":"bottom-panel","kind":"indicator","color":"#A855F7","catalogKeys":["dymi"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateDYMI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["dymi"]},"objectTreeIds":["dymi"],"children":[]},
  ultimateOsc: {"id":"ultimateOsc","key":"ultimate_osc","label":"Ultimate Osc","stateId":"ultimateOsc","panel":"bottom-panel","kind":"indicator","color":"#F43F5E","catalogKeys":["ultimate_osc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateUltimateOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["ultimateOsc"]},"objectTreeIds":["ultimateOsc"],"children":[]},
  dpo20: {"id":"dpo20","key":"dpo_20","label":"DPO 20","stateId":"dpo20","panel":"bottom-panel","kind":"indicator","color":"#06B6D4","catalogKeys":["dpo_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateDPO"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["dpo20"]},"objectTreeIds":["dpo20"],"children":[]},
  tsi: {"id":"tsi","key":"tsi","label":"TSI","stateId":"tsi","panel":"bottom-panel","kind":"indicator","color":"#8B5CF6","catalogKeys":["tsi","tsi_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateTSI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["tsi","tsi-line","tsi-signal"]},"objectTreeIds":["tsi","tsi-line","tsi-signal"],"children":[{"id":"tsi-line","label":"TSI","kind":"indicator","color":"#8B5CF6"},{"id":"tsi-signal","label":"TSI Signal","kind":"indicator","color":"#F59E0B"}]},
  awesomeOsc: {"id":"awesomeOsc","key":"awesome_osc","label":"Awesome Osc","stateId":"awesomeOsc","panel":"bottom-panel","kind":"indicator","color":"#26a69a","catalogKeys":["awesome_osc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateAwesomeOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["awesomeOsc"]},"objectTreeIds":["awesomeOsc"],"children":[]},
  acOsc: {"id":"acOsc","key":"ac_osc","label":"AC Osc","stateId":"acOsc","panel":"bottom-panel","kind":"indicator","color":"#26a69a","catalogKeys":["ac_osc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateAcceleratorOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["acOsc"]},"objectTreeIds":["acOsc"],"children":[]},
  rvi: {"id":"rvi","key":"rvi","label":"RVI","stateId":"rvi","panel":"bottom-panel","kind":"indicator","color":"#22d3ee","catalogKeys":["rvi","rvi_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateRVI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["rvi","rvi-line","rvi-signal"]},"objectTreeIds":["rvi","rvi-line","rvi-signal"],"children":[{"id":"rvi-line","label":"RVI","kind":"indicator","color":"#22d3ee"},{"id":"rvi-signal","label":"RVI Signal","kind":"indicator","color":"#facc15"}]},
  fisherTransform: {"id":"fisherTransform","key":"fisher_transform","label":"Fisher Transform","stateId":"fisherTransform","panel":"bottom-panel","kind":"indicator","color":"#e879f9","catalogKeys":["fisher_transform","fisher_transform_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateFisherTransform"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["fisherTransform","fisher-line","fisher-signal"]},"objectTreeIds":["fisherTransform","fisher-line","fisher-signal"],"children":[{"id":"fisher-line","label":"Fisher","kind":"indicator","color":"#e879f9"},{"id":"fisher-signal","label":"Fisher Signal","kind":"indicator","color":"#f59e0b"}]},
  elderBullBear: {"id":"elderBullBear","key":"elder_bull_power","label":"Elder Bull/Bear","stateId":"elderBullBear","panel":"bottom-panel","kind":"indicator","color":"#f97316","catalogKeys":["elder_bull_power","elder_bear_power"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateElderBullBearPower"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["elderBullBear","elder-bull","elder-bear"]},"objectTreeIds":["elderBullBear","elder-bull","elder-bear"],"children":[{"id":"elder-bull","label":"Elder Bull","kind":"indicator","color":"#22c55e"},{"id":"elder-bear","label":"Elder Bear","kind":"indicator","color":"#ef4444"}]},
  coppock: {"id":"coppock","key":"coppock_curve","label":"Coppock","stateId":"coppock","panel":"bottom-panel","kind":"indicator","color":"#84cc16","catalogKeys":["coppock_curve"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCoppockCurve"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["coppock"]},"objectTreeIds":["coppock"],"children":[]},
  ppo: {"id":"ppo","key":"macd_ppo","label":"PPO","stateId":"ppo","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["macd_ppo","macd_ppo_signal","macd_ppo_histogram"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePPO"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["ppo","ppo-line","ppo-signal","ppo-histogram"]},"objectTreeIds":["ppo","ppo-line","ppo-signal","ppo-histogram"],"children":[{"id":"ppo-line","label":"PPO Line","kind":"indicator","color":"#38bdf8"},{"id":"ppo-signal","label":"PPO Signal","kind":"indicator","color":"#f59e0b"},{"id":"ppo-histogram","label":"PPO Histogram","kind":"indicator","color":"#22c55e"}]},
  apo: {"id":"apo","key":"macd_apo","label":"APO","stateId":"apo","panel":"bottom-panel","kind":"indicator","color":"#f97316","catalogKeys":["macd_apo"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateAPO"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["apo"]},"objectTreeIds":["apo"],"children":[]},
  parabolicSar: {"id":"parabolicSar","key":"parabolic_sar","label":"Parabolic SAR","stateId":"parabolicSar","panel":"price-overlay","kind":"overlay","color":"#facc15","catalogKeys":["parabolic_sar","parabolic_sar_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateParabolicSAR"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["parabolicSar","parabolic-sar","parabolic-sar-signal"]},"objectTreeIds":["parabolicSar","parabolic-sar","parabolic-sar-signal"],"children":[{"id":"parabolic-sar","label":"SAR","kind":"overlay","color":"#facc15"},{"id":"parabolic-sar-signal","label":"SAR Signal","kind":"indicator","color":"#22c55e"}]},
  adx: {"id":"adx","key":"adx","label":"ADX","stateId":"adx","panel":"bottom-panel","kind":"indicator","color":"#22c55e","catalogKeys":["adx","adx_plus_di","adx_minus_di","adx_trend_strength"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateADX"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["adx","adx-line","adx-plus-di","adx-minus-di"]},"objectTreeIds":["adx","adx-line","adx-plus-di","adx-minus-di"],"children":[{"id":"adx-line","label":"ADX","kind":"indicator","color":"#c084fc"},{"id":"adx-plus-di","label":"+DI","kind":"indicator","color":"#22c55e"},{"id":"adx-minus-di","label":"-DI","kind":"indicator","color":"#ef4444"}]},
  aroon: {"id":"aroon","key":"aroon_up","label":"Aroon","stateId":"aroon","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["aroon_up","aroon_down"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateAroon"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["aroon","aroon-up","aroon-down"]},"objectTreeIds":["aroon","aroon-up","aroon-down"],"children":[{"id":"aroon-up","label":"Aroon Up","kind":"indicator","color":"#22c55e"},{"id":"aroon-down","label":"Aroon Down","kind":"indicator","color":"#ef4444"}]},
  aroonOsc: {"id":"aroonOsc","key":"aroon_oscillator","label":"Aroon Osc","stateId":"aroonOsc","panel":"bottom-panel","kind":"indicator","color":"#a78bfa","catalogKeys":["aroon_oscillator"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateAroonOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["aroonOsc"]},"objectTreeIds":["aroonOsc"],"children":[]},
  supertrend: {"id":"supertrend","key":"supertrend","label":"Supertrend","stateId":"supertrend","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["supertrend","supertrend_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateSupertrend"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["supertrend","supertrend-line","supertrend-line-up","supertrend-line-down","supertrend-signal"]},"objectTreeIds":["supertrend","supertrend-line","supertrend-line-up","supertrend-line-down","supertrend-signal"],"children":[{"id":"supertrend-line","label":"Supertrend","kind":"overlay","color":"#22c55e"},{"id":"supertrend-signal","label":"Supertrend Signal","kind":"indicator","color":"#facc15"}]},
  vortex: {"id":"vortex","key":"vortex_plus","label":"Vortex","stateId":"vortex","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["vortex_plus","vortex_minus"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateVortex"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["vortex","vortex-plus","vortex-minus"]},"objectTreeIds":["vortex","vortex-plus","vortex-minus"],"children":[{"id":"vortex-plus","label":"Vortex +","kind":"indicator","color":"#22c55e"},{"id":"vortex-minus","label":"Vortex -","kind":"indicator","color":"#ef4444"}]},
  trix: {"id":"trix","key":"trix","label":"TRIX","stateId":"trix","panel":"bottom-panel","kind":"indicator","color":"#f97316","catalogKeys":["trix"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateTRIX"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["trix"]},"objectTreeIds":["trix"],"children":[]},
  stc: {"id":"stc","key":"stc","label":"STC","stateId":"stc","panel":"bottom-panel","kind":"indicator","color":"#a855f7","catalogKeys":["stc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateSTC"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["stc"]},"objectTreeIds":["stc"],"children":[]},
  massIndex: {"id":"massIndex","key":"mass_index","label":"Mass Index","stateId":"massIndex","panel":"bottom-panel","kind":"indicator","color":"#f59e0b","catalogKeys":["mass_index"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMassIndex"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["massIndex"]},"objectTreeIds":["massIndex"],"children":[]},
  kst: {"id":"kst","key":"kst","label":"KST","stateId":"kst","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["kst","kst_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateKST"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["kst","kst-line","kst-signal"]},"objectTreeIds":["kst","kst-line","kst-signal"],"children":[{"id":"kst-line","label":"KST","kind":"indicator","color":"#38bdf8"},{"id":"kst-signal","label":"KST Signal","kind":"indicator","color":"#f59e0b"}]},
  linearRegression: {"id":"linearRegression","key":"linear_reg_value","label":"Linear Regression","stateId":"linearRegression","panel":"price-overlay","kind":"overlay","color":"#818cf8","catalogKeys":["linear_reg_value","linear_reg_slope"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateLinearRegressionIndicator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["linearRegression","linear-reg-value","linear-reg-slope"]},"objectTreeIds":["linearRegression","linear-reg-value","linear-reg-slope"],"children":[{"id":"linear-reg-value","label":"LinReg Value","kind":"overlay","color":"#818cf8"},{"id":"linear-reg-slope","label":"LinReg Slope","kind":"indicator","color":"#a78bfa"}]},
  ulcerIndex: {"id":"ulcerIndex","key":"ulcer_index","label":"Ulcer Index","stateId":"ulcerIndex","panel":"bottom-panel","kind":"indicator","color":"#e11d48","catalogKeys":["ulcer_index"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateUlcerIndex"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["ulcerIndex"]},"objectTreeIds":["ulcerIndex"],"children":[]},
  obv: {"id":"obv","key":"obv","label":"OBV","stateId":"obv","panel":"bottom-panel","kind":"indicator","color":"#FF5722","catalogKeys":["obv"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateOBV"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["obv"]},"objectTreeIds":["obv"],"children":[]},
  adLine: {"id":"adLine","key":"ad_line","label":"A/D Line","stateId":"adLine","panel":"bottom-panel","kind":"indicator","color":"#10b981","catalogKeys":["ad_line"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateADLine"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["adLine"]},"objectTreeIds":["adLine"],"children":[]},
  cmf20: {"id":"cmf20","key":"cmf_20","label":"CMF 20","stateId":"cmf20","panel":"bottom-panel","kind":"indicator","color":"#22c55e","catalogKeys":["cmf_20"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCMF"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["cmf20"]},"objectTreeIds":["cmf20"],"children":[]},
  nvi: {"id":"nvi","key":"nvi","label":"NVI","stateId":"nvi","panel":"bottom-panel","kind":"indicator","color":"#38bdf8","catalogKeys":["nvi"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateNVI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["nvi"]},"objectTreeIds":["nvi"],"children":[]},
  pvi: {"id":"pvi","key":"pvi","label":"PVI","stateId":"pvi","panel":"bottom-panel","kind":"indicator","color":"#f59e0b","catalogKeys":["pvi"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePVI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["pvi"]},"objectTreeIds":["pvi"],"children":[]},
  chaikinOsc: {"id":"chaikinOsc","key":"chaikin_osc","label":"Chaikin Oscillator","stateId":"chaikinOsc","panel":"bottom-panel","kind":"indicator","color":"#f97316","catalogKeys":["chaikin_osc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateChaikinOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["chaikinOsc"]},"objectTreeIds":["chaikinOsc"],"children":[]},
  volumeOsc: {"id":"volumeOsc","key":"volume_osc","label":"Volume Oscillator","stateId":"volumeOsc","panel":"bottom-panel","kind":"indicator","color":"#a855f7","catalogKeys":["volume_osc"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateVolumeOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["volumeOsc"]},"objectTreeIds":["volumeOsc"],"children":[]},
  vroc14: {"id":"vroc14","key":"vroc_14","label":"VROC 14","stateId":"vroc14","panel":"bottom-panel","kind":"indicator","color":"#22d3ee","catalogKeys":["vroc_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateVROC"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["vroc14"]},"objectTreeIds":["vroc14"],"children":[]},
  klinger: {"id":"klinger","key":"klinger_osc","label":"Klinger Oscillator","stateId":"klinger","panel":"bottom-panel","kind":"indicator","color":"#0ea5e9","catalogKeys":["klinger_osc","klinger_signal"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateKlingerOscillator"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["klinger","klinger-osc","klinger-signal"]},"objectTreeIds":["klinger","klinger-osc","klinger-signal"],"children":[{"id":"klinger-osc","label":"Klinger Osc","kind":"indicator","color":"#0ea5e9"},{"id":"klinger-signal","label":"Klinger Signal","kind":"indicator","color":"#f59e0b"}]},
  elderForceIndex: {"id":"elderForceIndex","key":"elder_force_raw","label":"Elder Force Index","stateId":"elderForceIndex","panel":"bottom-panel","kind":"indicator","color":"#f43f5e","catalogKeys":["elder_force_raw","force_index_13"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateElderForceIndex"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["elderForceIndex","elder-force-raw","force-index-13"]},"objectTreeIds":["elderForceIndex","elder-force-raw","force-index-13"],"children":[{"id":"elder-force-raw","label":"Elder Force Raw","kind":"indicator","color":"#fb7185"},{"id":"force-index-13","label":"Force Index 13","kind":"indicator","color":"#f43f5e"}]},
  eom14: {"id":"eom14","key":"eom_14","label":"EOM 14","stateId":"eom14","panel":"bottom-panel","kind":"indicator","color":"#8b5cf6","catalogKeys":["eom_14"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateEOM"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["eom14"]},"objectTreeIds":["eom14"],"children":[]},
  volumeProfile: {"id":"volumeProfile","key":"vp_poc","label":"Volume Profile","stateId":"volumeProfile","panel":"price-overlay","kind":"overlay","color":"#0ea5e9","catalogKeys":["vp_poc","vp_vah","vp_val"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateVolumeProfile"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["volumeProfile","volume-profile-rows","vp-poc","vp-vah","vp-val"]},"objectTreeIds":["volumeProfile","volume-profile-rows","vp-poc","vp-vah","vp-val"],"children":[{"id":"volume-profile-rows","label":"Volume Profile Rows","kind":"overlay","color":"#0ea5e9"},{"id":"vp-poc","label":"POC","kind":"overlay","color":"#f59e0b"},{"id":"vp-vah","label":"VAH","kind":"overlay","color":"#22d3ee"},{"id":"vp-val","label":"VAL","kind":"overlay","color":"#22d3ee"}]},
  pivotPointsStandard: {"id":"pivotPointsStandard","key":"pivot_standard","label":"Pivot Points Standard","stateId":"pivotPointsStandard","panel":"price-overlay","kind":"overlay","color":"#38bdf8","catalogKeys":["pivot_standard","pivot_r1","pivot_r2","pivot_r3","pivot_s1","pivot_s2","pivot_s3"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePivotPointsStandard"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["pivotPointsStandard","pivot-standard-p","pivot-standard-r1","pivot-standard-r2","pivot-standard-r3","pivot-standard-s1","pivot-standard-s2","pivot-standard-s3"]},"objectTreeIds":["pivotPointsStandard","pivot-standard-p","pivot-standard-r1","pivot-standard-r2","pivot-standard-r3","pivot-standard-s1","pivot-standard-s2","pivot-standard-s3"],"children":[{"id":"pivot-standard-p","label":"Pivot","kind":"overlay","color":"#cbd5e1"},{"id":"pivot-standard-r1","label":"R1","kind":"overlay","color":"#fb7185"},{"id":"pivot-standard-r2","label":"R2","kind":"overlay","color":"#f43f5e"},{"id":"pivot-standard-r3","label":"R3","kind":"overlay","color":"#e11d48"},{"id":"pivot-standard-s1","label":"S1","kind":"overlay","color":"#34d399"},{"id":"pivot-standard-s2","label":"S2","kind":"overlay","color":"#10b981"},{"id":"pivot-standard-s3","label":"S3","kind":"overlay","color":"#059669"}]},
  pivotPointsFibonacci: {"id":"pivotPointsFibonacci","key":"pivot_fib_p","label":"Pivot Points Fibonacci","stateId":"pivotPointsFibonacci","panel":"price-overlay","kind":"overlay","color":"#f59e0b","catalogKeys":["pivot_fib_p","pivot_fib_r1","pivot_fib_r2","pivot_fib_r3","pivot_fib_s1","pivot_fib_s2","pivot_fib_s3"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePivotPointsFibonacci"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["pivotPointsFibonacci","pivot-fib-p","pivot-fib-r1","pivot-fib-r2","pivot-fib-r3","pivot-fib-s1","pivot-fib-s2","pivot-fib-s3"]},"objectTreeIds":["pivotPointsFibonacci","pivot-fib-p","pivot-fib-r1","pivot-fib-r2","pivot-fib-r3","pivot-fib-s1","pivot-fib-s2","pivot-fib-s3"],"children":[{"id":"pivot-fib-p","label":"Pivot","kind":"overlay","color":"#c4b5fd"},{"id":"pivot-fib-r1","label":"Fib R1","kind":"overlay","color":"#fbbf24"},{"id":"pivot-fib-r2","label":"Fib R2","kind":"overlay","color":"#f59e0b"},{"id":"pivot-fib-r3","label":"Fib R3","kind":"overlay","color":"#d97706"},{"id":"pivot-fib-s1","label":"Fib S1","kind":"overlay","color":"#67e8f9"},{"id":"pivot-fib-s2","label":"Fib S2","kind":"overlay","color":"#22d3ee"},{"id":"pivot-fib-s3","label":"Fib S3","kind":"overlay","color":"#0891b2"}]},
  movingAverageCrosses: {"id":"movingAverageCrosses","key":"golden_cross","label":"Croisements de moyennes","stateId":"movingAverageCrosses","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["golden_cross","death_cross"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateMovingAverageCrossSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["movingAverageCrosses","golden-cross-marker","death-cross-marker"]},"objectTreeIds":["movingAverageCrosses","golden-cross-marker","death-cross-marker"],"children":[{"id":"golden-cross-marker","label":"Golden Cross","kind":"overlay","color":"#22c55e"},{"id":"death-cross-marker","label":"Death Cross","kind":"overlay","color":"#ef4444"}]},
  vwap: {"id":"vwap","key":"vwap","label":"VWAP","stateId":"vwap","panel":"price-overlay","kind":"overlay","color":"#14b8a6","catalogKeys":["vwap","is_above_vwap"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateVWAP"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["vwap","vwap-line","price-above-vwap-state"]},"objectTreeIds":["vwap","vwap-line","price-above-vwap-state"],"children":[{"id":"vwap-line","label":"VWAP","kind":"overlay","color":"#14b8a6"},{"id":"price-above-vwap-state","label":"Prix > VWAP","kind":"overlay","color":"#22c55e"}]},
  fiftyTwoWeekHigh: {"id":"fiftyTwoWeekHigh","key":"fifty_two_week_high","label":"52W High","stateId":"fiftyTwoWeekHigh","panel":"price-overlay","kind":"overlay","color":"#f97316","catalogKeys":["fifty_two_week_high"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateFiftyTwoWeekLevels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["fiftyTwoWeekHigh","52w-high-level","new-52w-high-marker"]},"objectTreeIds":["fiftyTwoWeekHigh","52w-high-level","new-52w-high-marker"],"children":[{"id":"52w-high-level","label":"52W High","kind":"overlay","color":"#f97316"},{"id":"new-52w-high-marker","label":"New 52W High","kind":"overlay","color":"#fb923c"}]},
  fiftyTwoWeekLow: {"id":"fiftyTwoWeekLow","key":"fifty_two_week_low","label":"52W Low","stateId":"fiftyTwoWeekLow","panel":"price-overlay","kind":"overlay","color":"#38bdf8","catalogKeys":["fifty_two_week_low"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateFiftyTwoWeekLevels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["fiftyTwoWeekLow","52w-low-level","new-52w-low-marker"]},"objectTreeIds":["fiftyTwoWeekLow","52w-low-level","new-52w-low-marker"],"children":[{"id":"52w-low-level","label":"52W Low","kind":"overlay","color":"#38bdf8"},{"id":"new-52w-low-marker","label":"New 52W Low","kind":"overlay","color":"#0ea5e9"}]},
  ath: {"id":"ath","key":"ath","label":"ATH","stateId":"ath","panel":"price-overlay","kind":"overlay","color":"#facc15","catalogKeys":["ath"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalRecordLevels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["ath","ath-level","new-ath-marker"]},"objectTreeIds":["ath","ath-level","new-ath-marker"],"children":[{"id":"ath-level","label":"ATH","kind":"overlay","color":"#facc15"},{"id":"new-ath-marker","label":"New ATH","kind":"overlay","color":"#fde047"}]},
  atl: {"id":"atl","key":"atl","label":"ATL","stateId":"atl","panel":"price-overlay","kind":"overlay","color":"#a78bfa","catalogKeys":["atl"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateHistoricalRecordLevels"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["atl","atl-level","new-atl-marker"]},"objectTreeIds":["atl","atl-level","new-atl-marker"],"children":[{"id":"atl-level","label":"ATL","kind":"overlay","color":"#a78bfa"},{"id":"new-atl-marker","label":"New ATL","kind":"overlay","color":"#c084fc"}]},
  breakoutResistance: {"id":"breakoutResistance","key":"breakout_resistance","label":"Breakout résistance","stateId":"breakoutResistance","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["breakout_resistance"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["breakoutResistance","breakout-resistance-marker"]},"objectTreeIds":["breakoutResistance","breakout-resistance-marker"],"children":[{"id":"breakout-resistance-marker","label":"Breakout résistance","kind":"overlay","color":"#22c55e"}]},
  breakdownSupport: {"id":"breakdownSupport","key":"breakdown_support","label":"Breakdown support","stateId":"breakdownSupport","panel":"price-overlay","kind":"overlay","color":"#f43f5e","catalogKeys":["breakdown_support"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["breakdownSupport","breakdown-support-marker"]},"objectTreeIds":["breakdownSupport","breakdown-support-marker"],"children":[{"id":"breakdown-support-marker","label":"Breakdown support","kind":"overlay","color":"#f43f5e"}]},
  gapUp: {"id":"gapUp","key":"gap_up","label":"Gap Up","stateId":"gapUp","panel":"price-overlay","kind":"overlay","color":"#22d3ee","catalogKeys":["gap_up"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["gapUp","gap-up-marker"]},"objectTreeIds":["gapUp","gap-up-marker"],"children":[{"id":"gap-up-marker","label":"Gap Up","kind":"overlay","color":"#22d3ee"}]},
  gapDown: {"id":"gapDown","key":"gap_down","label":"Gap Down","stateId":"gapDown","panel":"price-overlay","kind":"overlay","color":"#fb7185","catalogKeys":["gap_down"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["gapDown","gap-down-marker"]},"objectTreeIds":["gapDown","gap-down-marker"],"children":[{"id":"gap-down-marker","label":"Gap Down","kind":"overlay","color":"#fb7185"}]},
  trueGapUp: {"id":"trueGapUp","key":"true_gap_up","label":"True Gap Up","stateId":"trueGapUp","panel":"price-overlay","kind":"overlay","color":"#67e8f9","catalogKeys":["true_gap_up"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["trueGapUp","true-gap-up-marker"]},"objectTreeIds":["trueGapUp","true-gap-up-marker"],"children":[{"id":"true-gap-up-marker","label":"True Gap Up","kind":"overlay","color":"#67e8f9"}]},
  trueGapDown: {"id":"trueGapDown","key":"true_gap_down","label":"True Gap Down","stateId":"trueGapDown","panel":"price-overlay","kind":"overlay","color":"#fda4af","catalogKeys":["true_gap_down"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["trueGapDown","true-gap-down-marker"]},"objectTreeIds":["trueGapDown","true-gap-down-marker"],"children":[{"id":"true-gap-down-marker","label":"True Gap Down","kind":"overlay","color":"#fda4af"}]},
  gapPct: {"id":"gapPct","key":"gap_pct","label":"Gap %","stateId":"gapPct","panel":"price-overlay","kind":"overlay","color":"#e0f2fe","catalogKeys":["gap_pct"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["gapPct","gap-pct-label"]},"objectTreeIds":["gapPct","gap-pct-label"],"children":[{"id":"gap-pct-label","label":"Gap % labels","kind":"overlay","color":"#e0f2fe"}]},
  consecutiveUpDays: {"id":"consecutiveUpDays","key":"consecutive_up_days","label":"Jours hausse","stateId":"consecutiveUpDays","panel":"price-overlay","kind":"overlay","color":"#16a34a","catalogKeys":["consecutive_up_days"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["consecutiveUpDays","up-streak-badge"]},"objectTreeIds":["consecutiveUpDays","up-streak-badge"],"children":[{"id":"up-streak-badge","label":"Jours hausse","kind":"overlay","color":"#16a34a"}]},
  consecutiveDownDays: {"id":"consecutiveDownDays","key":"consecutive_down_days","label":"Jours baisse","stateId":"consecutiveDownDays","panel":"price-overlay","kind":"overlay","color":"#dc2626","catalogKeys":["consecutive_down_days"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["consecutiveDownDays","down-streak-badge"]},"objectTreeIds":["consecutiveDownDays","down-streak-badge"],"children":[{"id":"down-streak-badge","label":"Jours baisse","kind":"overlay","color":"#dc2626"}]},
  insideBar: {"id":"insideBar","key":"inside_bar","label":"Inside Bar","stateId":"insideBar","panel":"price-overlay","kind":"overlay","color":"#a78bfa","catalogKeys":["inside_bar"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["insideBar","inside-bar-outline"]},"objectTreeIds":["insideBar","inside-bar-outline"],"children":[{"id":"inside-bar-outline","label":"Inside Bar","kind":"overlay","color":"#a78bfa"}]},
  outsideBar: {"id":"outsideBar","key":"outside_bar","label":"Outside Bar","stateId":"outsideBar","panel":"price-overlay","kind":"overlay","color":"#f59e0b","catalogKeys":["outside_bar"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculatePriceActionSignals"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["outsideBar","outside-bar-outline"]},"objectTreeIds":["outsideBar","outside-bar-outline"],"children":[{"id":"outside-bar-outline","label":"Outside Bar","kind":"overlay","color":"#f59e0b"}]},
  doji: {"id":"doji","key":"pattern_doji","label":"Doji","stateId":"doji","panel":"price-overlay","kind":"overlay","color":"#94a3b8","catalogKeys":["pattern_doji"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["doji","doji-marker"]},"objectTreeIds":["doji","doji-marker"],"children":[{"id":"doji-marker","label":"Doji","kind":"overlay","color":"#94a3b8"}]},
  longLeggedDoji: {"id":"longLeggedDoji","key":"pattern_doji_longleg","label":"Long-legged Doji","stateId":"longLeggedDoji","panel":"price-overlay","kind":"overlay","color":"#fbbf24","catalogKeys":["pattern_doji_longleg"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["longLeggedDoji","long-legged-doji-marker"]},"objectTreeIds":["longLeggedDoji","long-legged-doji-marker"],"children":[{"id":"long-legged-doji-marker","label":"Long-legged Doji","kind":"overlay","color":"#fbbf24"}]},
  rickshawMan: {"id":"rickshawMan","key":"pattern_rickshaw_man","label":"Rickshaw Man","stateId":"rickshawMan","panel":"price-overlay","kind":"overlay","color":"#c084fc","catalogKeys":["pattern_rickshaw_man"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["rickshawMan","rickshaw-man-marker"]},"objectTreeIds":["rickshawMan","rickshaw-man-marker"],"children":[{"id":"rickshaw-man-marker","label":"Rickshaw Man","kind":"overlay","color":"#c084fc"}]},
  dragonflyDoji: {"id":"dragonflyDoji","key":"pattern_doji_dragonfly","label":"Dragonfly Doji","stateId":"dragonflyDoji","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["pattern_doji_dragonfly"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["dragonflyDoji","dragonfly-doji-marker"]},"objectTreeIds":["dragonflyDoji","dragonfly-doji-marker"],"children":[{"id":"dragonfly-doji-marker","label":"Dragonfly Doji","kind":"overlay","color":"#22c55e"}]},
  gravestoneDoji: {"id":"gravestoneDoji","key":"pattern_doji_gravestone","label":"Gravestone Doji","stateId":"gravestoneDoji","panel":"price-overlay","kind":"overlay","color":"#f43f5e","catalogKeys":["pattern_doji_gravestone"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["gravestoneDoji","gravestone-doji-marker"]},"objectTreeIds":["gravestoneDoji","gravestone-doji-marker"],"children":[{"id":"gravestone-doji-marker","label":"Gravestone Doji","kind":"overlay","color":"#f43f5e"}]},
  tristar: {"id":"tristar","key":"pattern_tristar","label":"Tristar","stateId":"tristar","panel":"price-overlay","kind":"overlay","color":"#38bdf8","catalogKeys":["pattern_tristar"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["tristar","tristar-zone"]},"objectTreeIds":["tristar","tristar-zone"],"children":[{"id":"tristar-zone","label":"Tristar","kind":"overlay","color":"#38bdf8"}]},
  hammer: {"id":"hammer","key":"pattern_hammer","label":"Hammer","stateId":"hammer","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["pattern_hammer"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["hammer","hammer-marker"]},"objectTreeIds":["hammer","hammer-marker"],"children":[{"id":"hammer-marker","label":"Hammer","kind":"overlay","color":"#22c55e"}]},
  hangingMan: {"id":"hangingMan","key":"pattern_hanging_man","label":"Hanging Man","stateId":"hangingMan","panel":"price-overlay","kind":"overlay","color":"#f97316","catalogKeys":["pattern_hanging_man"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["hangingMan","hanging-man-marker"]},"objectTreeIds":["hangingMan","hanging-man-marker"],"children":[{"id":"hanging-man-marker","label":"Hanging Man","kind":"overlay","color":"#f97316"}]},
  takuri: {"id":"takuri","key":"pattern_takuri","label":"Takuri","stateId":"takuri","panel":"price-overlay","kind":"overlay","color":"#14b8a6","catalogKeys":["pattern_takuri"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["takuri","takuri-marker"]},"objectTreeIds":["takuri","takuri-marker"],"children":[{"id":"takuri-marker","label":"Takuri","kind":"overlay","color":"#14b8a6"}]},
  invertedHammer: {"id":"invertedHammer","key":"pattern_inv_hammer","label":"Inverted Hammer","stateId":"invertedHammer","panel":"price-overlay","kind":"overlay","color":"#38bdf8","catalogKeys":["pattern_inv_hammer"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["invertedHammer","inverted-hammer-marker"]},"objectTreeIds":["invertedHammer","inverted-hammer-marker"],"children":[{"id":"inverted-hammer-marker","label":"Inverted Hammer","kind":"overlay","color":"#38bdf8"}]},
  shootingStar: {"id":"shootingStar","key":"pattern_shooting_star","label":"Shooting Star","stateId":"shootingStar","panel":"price-overlay","kind":"overlay","color":"#be123c","catalogKeys":["pattern_shooting_star"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["shootingStar","shooting-star-marker"]},"objectTreeIds":["shootingStar","shooting-star-marker"],"children":[{"id":"shooting-star-marker","label":"Shooting Star","kind":"overlay","color":"#be123c"}]},
  engulfingBullish: {"id":"engulfingBullish","key":"pattern_engulfing_bull","label":"Engulfing Bullish","stateId":"engulfingBullish","panel":"price-overlay","kind":"overlay","color":"#16a34a","catalogKeys":["pattern_engulfing_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["engulfingBullish","engulfing-bullish-bracket"]},"objectTreeIds":["engulfingBullish","engulfing-bullish-bracket"],"children":[{"id":"engulfing-bullish-bracket","label":"Engulfing Bullish","kind":"overlay","color":"#16a34a"}]},
  engulfingBearish: {"id":"engulfingBearish","key":"pattern_engulfing_bear","label":"Engulfing Bearish","stateId":"engulfingBearish","panel":"price-overlay","kind":"overlay","color":"#dc2626","catalogKeys":["pattern_engulfing_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["engulfingBearish","engulfing-bearish-bracket"]},"objectTreeIds":["engulfingBearish","engulfing-bearish-bracket"],"children":[{"id":"engulfing-bearish-bracket","label":"Engulfing Bearish","kind":"overlay","color":"#dc2626"}]},
  haramiBullish: {"id":"haramiBullish","key":"pattern_harami_bull","label":"Harami Bullish","stateId":"haramiBullish","panel":"price-overlay","kind":"overlay","color":"#0ea5e9","catalogKeys":["pattern_harami_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["haramiBullish","harami-bullish-bracket"]},"objectTreeIds":["haramiBullish","harami-bullish-bracket"],"children":[{"id":"harami-bullish-bracket","label":"Harami Bullish","kind":"overlay","color":"#0ea5e9"}]},
  haramiBearish: {"id":"haramiBearish","key":"pattern_harami_bear","label":"Harami Bearish","stateId":"haramiBearish","panel":"price-overlay","kind":"overlay","color":"#f97316","catalogKeys":["pattern_harami_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["haramiBearish","harami-bearish-bracket"]},"objectTreeIds":["haramiBearish","harami-bearish-bracket"],"children":[{"id":"harami-bearish-bracket","label":"Harami Bearish","kind":"overlay","color":"#f97316"}]},
  tweezerTop: {"id":"tweezerTop","key":"pattern_tweezer_top","label":"Tweezer Top","stateId":"tweezerTop","panel":"price-overlay","kind":"overlay","color":"#e11d48","catalogKeys":["pattern_tweezer_top"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["tweezerTop","tweezer-top-line"]},"objectTreeIds":["tweezerTop","tweezer-top-line"],"children":[{"id":"tweezer-top-line","label":"Tweezer Top","kind":"overlay","color":"#e11d48"}]},
  tweezerBottom: {"id":"tweezerBottom","key":"pattern_tweezer_bottom","label":"Tweezer Bottom","stateId":"tweezerBottom","panel":"price-overlay","kind":"overlay","color":"#0891b2","catalogKeys":["pattern_tweezer_bottom"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["tweezerBottom","tweezer-bottom-line"]},"objectTreeIds":["tweezerBottom","tweezer-bottom-line"],"children":[{"id":"tweezer-bottom-line","label":"Tweezer Bottom","kind":"overlay","color":"#0891b2"}]},
  piercingLine: {"id":"piercingLine","key":"pattern_piercing_line","label":"Piercing Line","stateId":"piercingLine","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["pattern_piercing_line"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["piercingLine","piercing-line-marker"]},"objectTreeIds":["piercingLine","piercing-line-marker"],"children":[{"id":"piercing-line-marker","label":"Piercing Line","kind":"overlay","color":"#22c55e"}]},
  darkCloudCover: {"id":"darkCloudCover","key":"pattern_dark_cloud_cover","label":"Dark Cloud Cover","stateId":"darkCloudCover","panel":"price-overlay","kind":"overlay","color":"#b91c1c","catalogKeys":["pattern_dark_cloud_cover"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["darkCloudCover","dark-cloud-cover-marker"]},"objectTreeIds":["darkCloudCover","dark-cloud-cover-marker"],"children":[{"id":"dark-cloud-cover-marker","label":"Dark Cloud Cover","kind":"overlay","color":"#b91c1c"}]},
  tasukiGap: {"id":"tasukiGap","key":"pattern_tasuki_gap","label":"Tasuki Gap","stateId":"tasukiGap","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["pattern_tasuki_gap"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["tasukiGap","tasuki-gap-bracket"]},"objectTreeIds":["tasukiGap","tasuki-gap-bracket"],"children":[{"id":"tasuki-gap-bracket","label":"Tasuki Gap","kind":"overlay","color":"#22c55e"}]},
  separatingLines: {"id":"separatingLines","key":"pattern_separating_lines","label":"Separating Lines","stateId":"separatingLines","panel":"price-overlay","kind":"overlay","color":"#38bdf8","catalogKeys":["pattern_separating_lines"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["separatingLines","separating-lines-marker"]},"objectTreeIds":["separatingLines","separating-lines-marker"],"children":[{"id":"separating-lines-marker","label":"Separating Lines","kind":"overlay","color":"#38bdf8"}]},
  thrusting: {"id":"thrusting","key":"pattern_thrusting","label":"Thrusting","stateId":"thrusting","panel":"price-overlay","kind":"overlay","color":"#f97316","catalogKeys":["pattern_thrusting"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["thrusting","thrusting-marker"]},"objectTreeIds":["thrusting","thrusting-marker"],"children":[{"id":"thrusting-marker","label":"Thrusting","kind":"overlay","color":"#f97316"}]},
  counterattack: {"id":"counterattack","key":"pattern_counterattack","label":"Counterattack","stateId":"counterattack","panel":"price-overlay","kind":"overlay","color":"#a855f7","catalogKeys":["pattern_counterattack"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["counterattack","counterattack-bracket"]},"objectTreeIds":["counterattack","counterattack-bracket"],"children":[{"id":"counterattack-bracket","label":"Counterattack","kind":"overlay","color":"#a855f7"}]},
  morningStar: {"id":"morningStar","key":"pattern_morning_star","label":"Morning Star","stateId":"morningStar","panel":"price-overlay","kind":"overlay","color":"#10b981","catalogKeys":["pattern_morning_star"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["morningStar","morning-star-bracket"]},"objectTreeIds":["morningStar","morning-star-bracket"],"children":[{"id":"morning-star-bracket","label":"Morning Star","kind":"overlay","color":"#10b981"}]},
  eveningStar: {"id":"eveningStar","key":"pattern_evening_star","label":"Evening Star","stateId":"eveningStar","panel":"price-overlay","kind":"overlay","color":"#ef4444","catalogKeys":["pattern_evening_star"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["eveningStar","evening-star-bracket"]},"objectTreeIds":["eveningStar","evening-star-bracket"],"children":[{"id":"evening-star-bracket","label":"Evening Star","kind":"overlay","color":"#ef4444"}]},
  threeWhiteSoldiers: {"id":"threeWhiteSoldiers","key":"pattern_3_white_soldiers","label":"Three White Soldiers","stateId":"threeWhiteSoldiers","panel":"price-overlay","kind":"overlay","color":"#65a30d","catalogKeys":["pattern_3_white_soldiers"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["threeWhiteSoldiers","three-white-soldiers-bracket"]},"objectTreeIds":["threeWhiteSoldiers","three-white-soldiers-bracket"],"children":[{"id":"three-white-soldiers-bracket","label":"Three White Soldiers","kind":"overlay","color":"#65a30d"}]},
  threeBlackCrows: {"id":"threeBlackCrows","key":"pattern_3_black_crows","label":"Three Black Crows","stateId":"threeBlackCrows","panel":"price-overlay","kind":"overlay","color":"#991b1b","catalogKeys":["pattern_3_black_crows"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["threeBlackCrows","three-black-crows-bracket"]},"objectTreeIds":["threeBlackCrows","three-black-crows-bracket"],"children":[{"id":"three-black-crows-bracket","label":"Three Black Crows","kind":"overlay","color":"#991b1b"}]},
  threeInsideUp: {"id":"threeInsideUp","key":"pattern_3_inside_up","label":"Three Inside Up","stateId":"threeInsideUp","panel":"price-overlay","kind":"overlay","color":"#22c55e","catalogKeys":["pattern_3_inside_up"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["threeInsideUp","three-inside-up-bracket"]},"objectTreeIds":["threeInsideUp","three-inside-up-bracket"],"children":[{"id":"three-inside-up-bracket","label":"Three Inside Up","kind":"overlay","color":"#22c55e"}]},
  threeInsideDown: {"id":"threeInsideDown","key":"pattern_3_inside_down","label":"Three Inside Down","stateId":"threeInsideDown","panel":"price-overlay","kind":"overlay","color":"#dc2626","catalogKeys":["pattern_3_inside_down"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["threeInsideDown","three-inside-down-bracket"]},"objectTreeIds":["threeInsideDown","three-inside-down-bracket"],"children":[{"id":"three-inside-down-bracket","label":"Three Inside Down","kind":"overlay","color":"#dc2626"}]},
  uniqueThreeRiver: {"id":"uniqueThreeRiver","key":"pattern_unique_3_river","label":"Unique Three River","stateId":"uniqueThreeRiver","panel":"price-overlay","kind":"overlay","color":"#14b8a6","catalogKeys":["pattern_unique_3_river"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["uniqueThreeRiver","unique-three-river-bracket"]},"objectTreeIds":["uniqueThreeRiver","unique-three-river-bracket"],"children":[{"id":"unique-three-river-bracket","label":"Unique Three River","kind":"overlay","color":"#14b8a6"}]},
  upsideGapTwoCrows: {"id":"upsideGapTwoCrows","key":"pattern_upside_gap_two_crows","label":"Upside Gap Two Crows","stateId":"upsideGapTwoCrows","panel":"price-overlay","kind":"overlay","color":"#b91c1c","catalogKeys":["pattern_upside_gap_two_crows"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["upsideGapTwoCrows","upside-gap-two-crows-bracket"]},"objectTreeIds":["upsideGapTwoCrows","upside-gap-two-crows-bracket"],"children":[{"id":"upside-gap-two-crows-bracket","label":"Upside Gap Two Crows","kind":"overlay","color":"#b91c1c"}]},
  kickerBull: {"id":"kickerBull","key":"pattern_kicker_bull","label":"Kicker Bull","stateId":"kickerBull","panel":"price-overlay","kind":"overlay","color":"#16a34a","catalogKeys":["pattern_kicker_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["kickerBull","kicker-bull-bracket"]},"objectTreeIds":["kickerBull","kicker-bull-bracket"],"children":[{"id":"kicker-bull-bracket","label":"Kicker Bull","kind":"overlay","color":"#16a34a"}]},
  kickerBear: {"id":"kickerBear","key":"pattern_kicker_bear","label":"Kicker Bear","stateId":"kickerBear","panel":"price-overlay","kind":"overlay","color":"#ef4444","catalogKeys":["pattern_kicker_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["kickerBear","kicker-bear-bracket"]},"objectTreeIds":["kickerBear","kicker-bear-bracket"],"children":[{"id":"kicker-bear-bracket","label":"Kicker Bear","kind":"overlay","color":"#ef4444"}]},
  abandonedBabyBull: {"id":"abandonedBabyBull","key":"pattern_abandoned_baby_bull","label":"Abandoned Baby Bull","stateId":"abandonedBabyBull","panel":"price-overlay","kind":"overlay","color":"#0d9488","catalogKeys":["pattern_abandoned_baby_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["abandonedBabyBull","abandoned-baby-bull-bracket"]},"objectTreeIds":["abandonedBabyBull","abandoned-baby-bull-bracket"],"children":[{"id":"abandoned-baby-bull-bracket","label":"Abandoned Baby Bull","kind":"overlay","color":"#0d9488"}]},
  abandonedBabyBear: {"id":"abandonedBabyBear","key":"pattern_abandoned_baby_bear","label":"Abandoned Baby Bear","stateId":"abandonedBabyBear","panel":"price-overlay","kind":"overlay","color":"#e11d48","catalogKeys":["pattern_abandoned_baby_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["abandonedBabyBear","abandoned-baby-bear-bracket"]},"objectTreeIds":["abandonedBabyBear","abandoned-baby-bear-bracket"],"children":[{"id":"abandoned-baby-bear-bracket","label":"Abandoned Baby Bear","kind":"overlay","color":"#e11d48"}]},
  beltHoldBull: {"id":"beltHoldBull","key":"pattern_belthold_bull","label":"Belt Hold Bull","stateId":"beltHoldBull","panel":"price-overlay","kind":"overlay","color":"#84cc16","catalogKeys":["pattern_belthold_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["beltHoldBull","belt-hold-bull-marker"]},"objectTreeIds":["beltHoldBull","belt-hold-bull-marker"],"children":[{"id":"belt-hold-bull-marker","label":"Belt Hold Bull","kind":"overlay","color":"#84cc16"}]},
  beltHoldBear: {"id":"beltHoldBear","key":"pattern_belthold_bear","label":"Belt Hold Bear","stateId":"beltHoldBear","panel":"price-overlay","kind":"overlay","color":"#f97316","catalogKeys":["pattern_belthold_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["beltHoldBear","belt-hold-bear-marker"]},"objectTreeIds":["beltHoldBear","belt-hold-bear-marker"],"children":[{"id":"belt-hold-bear-marker","label":"Belt Hold Bear","kind":"overlay","color":"#f97316"}]},
  breakawayBull: {"id":"breakawayBull","key":"pattern_breakaway_bull","label":"Breakaway Bull","stateId":"breakawayBull","panel":"price-overlay","kind":"overlay","color":"#10b981","catalogKeys":["pattern_breakaway_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["breakawayBull","breakaway-bull-bracket"]},"objectTreeIds":["breakawayBull","breakaway-bull-bracket"],"children":[{"id":"breakaway-bull-bracket","label":"Breakaway Bull","kind":"overlay","color":"#10b981"}]},
  breakawayBear: {"id":"breakawayBear","key":"pattern_breakaway_bear","label":"Breakaway Bear","stateId":"breakawayBear","panel":"price-overlay","kind":"overlay","color":"#7f1d1d","catalogKeys":["pattern_breakaway_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["breakawayBear","breakaway-bear-bracket"]},"objectTreeIds":["breakawayBear","breakaway-bear-bracket"],"children":[{"id":"breakaway-bear-bracket","label":"Breakaway Bear","kind":"overlay","color":"#7f1d1d"}]},
  risingThreeMethods: {"id":"risingThreeMethods","key":"pattern_rising_three_methods","label":"Rising Three Methods","stateId":"risingThreeMethods","panel":"price-overlay","kind":"overlay","color":"#15803d","catalogKeys":["pattern_rising_three_methods"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["risingThreeMethods","rising-three-methods-bracket"]},"objectTreeIds":["risingThreeMethods","rising-three-methods-bracket"],"children":[{"id":"rising-three-methods-bracket","label":"Rising Three Methods","kind":"overlay","color":"#15803d"}]},
  fallingThreeMethods: {"id":"fallingThreeMethods","key":"pattern_falling_three_methods","label":"Falling Three Methods","stateId":"fallingThreeMethods","panel":"price-overlay","kind":"overlay","color":"#b91c1c","catalogKeys":["pattern_falling_three_methods"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["fallingThreeMethods","falling-three-methods-bracket"]},"objectTreeIds":["fallingThreeMethods","falling-three-methods-bracket"],"children":[{"id":"falling-three-methods-bracket","label":"Falling Three Methods","kind":"overlay","color":"#b91c1c"}]},
  matHold: {"id":"matHold","key":"pattern_mat_hold","label":"Mat Hold","stateId":"matHold","panel":"price-overlay","kind":"overlay","color":"#0f766e","catalogKeys":["pattern_mat_hold"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["matHold","mat-hold-bracket"]},"objectTreeIds":["matHold","mat-hold-bracket"],"children":[{"id":"mat-hold-bracket","label":"Mat Hold","kind":"overlay","color":"#0f766e"}]},
  gapSideBySideWhite: {"id":"gapSideBySideWhite","key":"pattern_gap_side_side_white","label":"Gap Side-by-Side White","stateId":"gapSideBySideWhite","panel":"price-overlay","kind":"overlay","color":"#d97706","catalogKeys":["pattern_gap_side_side_white"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["gapSideBySideWhite","gap-side-by-side-white-bracket"]},"objectTreeIds":["gapSideBySideWhite","gap-side-by-side-white-bracket"],"children":[{"id":"gap-side-by-side-white-bracket","label":"Gap Side-by-Side White","kind":"overlay","color":"#d97706"}]},
  hikkake: {"id":"hikkake","key":"pattern_hikkake","label":"Hikkake","stateId":"hikkake","panel":"price-overlay","kind":"overlay","color":"#7c3aed","catalogKeys":["pattern_hikkake"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["hikkake","hikkake-bracket"]},"objectTreeIds":["hikkake","hikkake-bracket"],"children":[{"id":"hikkake-bracket","label":"Hikkake","kind":"overlay","color":"#7c3aed"}]},
  concealingBabySwallow: {"id":"concealingBabySwallow","key":"pattern_concealing_baby_swallow","label":"Concealing Baby Swallow","stateId":"concealingBabySwallow","panel":"price-overlay","kind":"overlay","color":"#0891b2","catalogKeys":["pattern_concealing_baby_swallow"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["concealingBabySwallow","concealing-baby-swallow-bracket"]},"objectTreeIds":["concealingBabySwallow","concealing-baby-swallow-bracket"],"children":[{"id":"concealing-baby-swallow-bracket","label":"Concealing Baby Swallow","kind":"overlay","color":"#0891b2"}]},
  ladderBottom: {"id":"ladderBottom","key":"pattern_ladder_bottom","label":"Ladder Bottom","stateId":"ladderBottom","panel":"price-overlay","kind":"overlay","color":"#65a30d","catalogKeys":["pattern_ladder_bottom"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["ladderBottom","ladder-bottom-bracket"]},"objectTreeIds":["ladderBottom","ladder-bottom-bracket"],"children":[{"id":"ladder-bottom-bracket","label":"Ladder Bottom","kind":"overlay","color":"#65a30d"}]},
  stickSandwich: {"id":"stickSandwich","key":"pattern_stick_sandwich","label":"Stick Sandwich","stateId":"stickSandwich","panel":"price-overlay","kind":"overlay","color":"#b45309","catalogKeys":["pattern_stick_sandwich"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["stickSandwich","stick-sandwich-bracket"]},"objectTreeIds":["stickSandwich","stick-sandwich-bracket"],"children":[{"id":"stick-sandwich-bracket","label":"Stick Sandwich","kind":"overlay","color":"#b45309"}]},
  marubozuBull: {"id":"marubozuBull","key":"pattern_marubozu_bull","label":"Marubozu Bull","stateId":"marubozuBull","panel":"price-overlay","kind":"overlay","color":"#2563eb","catalogKeys":["pattern_marubozu_bull"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["marubozuBull","marubozu-bull-outline"]},"objectTreeIds":["marubozuBull","marubozu-bull-outline"],"children":[{"id":"marubozu-bull-outline","label":"Marubozu Bull","kind":"overlay","color":"#2563eb"}]},
  marubozuBear: {"id":"marubozuBear","key":"pattern_marubozu_bear","label":"Marubozu Bear","stateId":"marubozuBear","panel":"price-overlay","kind":"overlay","color":"#dc2626","catalogKeys":["pattern_marubozu_bear"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["marubozuBear","marubozu-bear-outline"]},"objectTreeIds":["marubozuBear","marubozu-bear-outline"],"children":[{"id":"marubozu-bear-outline","label":"Marubozu Bear","kind":"overlay","color":"#dc2626"}]},
  spinningTop: {"id":"spinningTop","key":"pattern_spinning_top","label":"Spinning Top","stateId":"spinningTop","panel":"price-overlay","kind":"overlay","color":"#a3a3a3","catalogKeys":["pattern_spinning_top"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateCandlestickPatterns"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["spinningTop","spinning-top-marker"]},"objectTreeIds":["spinningTop","spinning-top-marker"],"children":[{"id":"spinning-top-marker","label":"Spinning Top","kind":"overlay","color":"#a3a3a3"}]},
  ichimoku: {"id":"ichimoku","key":"ichimoku_tenkan","label":"Ichimoku","stateId":"ichimoku","panel":"price-overlay","kind":"overlay","color":"#2962FF","catalogKeys":["ichimoku_tenkan","ichimoku_kijun","ichimoku_senkou_a","ichimoku_senkou_b","ichimoku_chikou","ichimoku_cloud_color","price_vs_cloud"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateIchimoku"]},"renderer":{"source":"useEChartsRenderer.ts","target":"price-overlay","objectTreeIds":["ichimoku","ichimoku-tenkan","ichimoku-kijun","ichimoku-chikou","ichimoku-senkouA","ichimoku-senkouB","ichimoku-cloud"]},"objectTreeIds":["ichimoku","ichimoku-tenkan","ichimoku-kijun","ichimoku-chikou","ichimoku-senkouA","ichimoku-senkouB","ichimoku-cloud"],"children":[{"id":"ichimoku-tenkan","label":"Tenkan","kind":"overlay","color":"#2962FF"},{"id":"ichimoku-kijun","label":"Kijun","kind":"overlay","color":"#B71C1C"},{"id":"ichimoku-chikou","label":"Chikou","kind":"overlay","color":"#43A047"},{"id":"ichimoku-senkouA","label":"Senkou A","kind":"overlay","color":"#A5D6A7"},{"id":"ichimoku-senkouB","label":"Senkou B","kind":"overlay","color":"#EF9A9A"},{"id":"ichimoku-cloud","label":"Kumo Cloud","kind":"overlay","color":"#66bb6a"}]},
  stochRsi: {"id":"stochRsi","key":"stoch_rsi_k","label":"Stochastic RSI","stateId":"stochRsi","panel":"bottom-panel","kind":"indicator","color":"#00BCD4","catalogKeys":["stoch_rsi_k","stoch_rsi_d"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateStochasticRSI"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["stochRsi","stochrsi-k","stochrsi-d"]},"objectTreeIds":["stochRsi","stochrsi-k","stochrsi-d"],"children":[{"id":"stochrsi-k","label":"StochRSI %K","kind":"indicator","color":"#2962FF"},{"id":"stochrsi-d","label":"StochRSI %D","kind":"indicator","color":"#FF6D00"}]},
  bbWidth: {"id":"bbWidth","key":"bb_width","label":"BB Width","stateId":"bbWidth","panel":"bottom-panel","kind":"indicator","color":"#FF6D00","catalogKeys":["bb_width"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateBollinger"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["bbWidth"]},"objectTreeIds":["bbWidth"],"children":[]},
  bbPercentB: {"id":"bbPercentB","key":"bb_pct","label":"BB %B","stateId":"bbPercentB","panel":"bottom-panel","kind":"indicator","color":"#2962FF","catalogKeys":["bb_pct"],"formula":{"source":"TechnicalIndicators.ts","functions":["calculateBollinger"]},"renderer":{"source":"useEChartsRenderer.ts","target":"bottom-panel","objectTreeIds":["bbPercentB"]},"objectTreeIds":["bbPercentB"],"children":[]},
});

export const ADVANCED_INDICATOR_REGISTRY_ENTRIES: readonly AdvancedIndicatorRegistryEntry[] = Object.values(ADVANCED_INDICATOR_REGISTRY);

export const ADVANCED_INDICATOR_IDS = Object.keys(ADVANCED_INDICATOR_REGISTRY) as AdvancedIndicatorId[];

const MIXED_BOTTOM_PANEL_SLOT_INDICATOR_IDS = new Set<AdvancedIndicatorId>(["linearRegression"]);

export const BOTTOM_PANEL_INDICATOR_IDS = ADVANCED_INDICATOR_REGISTRY_ENTRIES
  .filter((entry) => entry.panel === "bottom-panel" || MIXED_BOTTOM_PANEL_SLOT_INDICATOR_IDS.has(entry.id))
  .map((entry) => entry.id);

export const isAdvancedIndicatorRegistryId = (id: string): id is AdvancedIndicatorId =>
  Object.prototype.hasOwnProperty.call(ADVANCED_INDICATOR_REGISTRY, id);

export const getAdvancedIndicatorRegistryEntry = (id: AdvancedIndicatorId): AdvancedIndicatorRegistryEntry =>
  ADVANCED_INDICATOR_REGISTRY[id];

export const getAdvancedIndicatorObjectIdsFromRegistry = (id: AdvancedIndicatorId): string[] =>
  [...ADVANCED_INDICATOR_REGISTRY[id].objectTreeIds];

export const getAdvancedIndicatorIdForObjectIdFromRegistry = (objectId: string): AdvancedIndicatorId | null =>
  ADVANCED_INDICATOR_REGISTRY_ENTRIES.find((entry) => entry.objectTreeIds.includes(objectId))?.id ?? null;

export const getAdvancedIndicatorLabelMetaFromRegistry = (id: AdvancedIndicatorId) => ({
  label: ADVANCED_INDICATOR_REGISTRY[id].label,
  kind: ADVANCED_INDICATOR_REGISTRY[id].kind,
  color: ADVANCED_INDICATOR_REGISTRY[id].color,
});

export const getAdvancedIndicatorChildGroupsFromRegistry = () =>
  ADVANCED_INDICATOR_REGISTRY_ENTRIES
    .filter((entry) => entry.children.length > 0)
    .map((entry) => ({
      indicator: entry.id,
      items: entry.children,
    }));
